import test from 'node:test';
import assert from 'node:assert/strict';
import { access, mkdtemp, mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { tmpdir } from 'node:os';
import { run } from '../core.mjs';
import { adaptFrontmatter, checkLinks, compareDsh, DSH_DEFAULTS, installDsh, loadDiscovery, previewDsh, skipReason } from '../dsh.mjs';

// The real DSH parser from this machine's DSH install; the flow tests need it to mean anything.
const MODULES = DSH_DEFAULTS.modules;
const haveDsh = await access(path.join(MODULES, '@deepseek-ai', 'dsh-skill-filesystem', 'lib', 'index.js')).then(() => true, () => false);
const put = async (dir, file, text) => { await mkdir(path.dirname(path.join(dir, file)), { recursive: true }); await writeFile(path.join(dir, file), text); };
const commit = async (dir, message) => { await run('git', ['-C', dir, 'add', '-A']); await run('git', ['-C', dir, '-c', 'user.name=Test', '-c', 'user.email=test@example.com', 'commit', '-qm', message]); };
const ADAPTER = '---\nname: delta\ndescription: Use when testing adapters that only point back at the Claude copy.\n---\n\n<!-- Generated by .claude/scripts/sync-codex-skills.mjs. Do not edit. -->\n';

// Source: alpha (bundle with references, a script, a secret and a cache), beta (no name, colon in
// an unquoted description), gamma (Codex-only native copy), delta (generated adapter only),
// mismatch (name differs from folder), linky (broken relative link), PROVENANCE.md (not a skill).
// The checkout carries an uncommitted edit that must never reach DSH.
async function fixture(t) {
  const temp = await mkdtemp(path.join(tmpdir(), 'corewise-dsh-test-'));
  t.after(() => rm(temp, { recursive: true, force: true }));
  const seed = path.join(temp, 'seed'); await run('git', ['init', '-q', '-b', 'main', seed]);
  const files = {
    '.claude/skills/alpha/SKILL.md': '---\nname: alpha\ndescription: Use when testing a complete bundle with references and scripts.\n---\n\nRead [the guide](references/guide.md) and run `scripts/run.mjs`. Project notes live in `.claude/reference/pitfalls.md`.\n',
    '.claude/skills/alpha/references/guide.md': 'Guide. Back to [the skill](../SKILL.md).\n',
    '.claude/skills/alpha/scripts/run.mjs': 'export {};\n',
    '.claude/skills/alpha/.env': 'TOKEN=secret\n',
    '.claude/skills/alpha/node_modules/dep/index.js': 'module.exports = 1;\n',
    '.claude/skills/beta/SKILL.md': '---\ndescription: Use when testing: a colon inside a plain description.\n---\n\nBeta body uses `$ARGUMENTS`.\n',
    '.agents/skills/gamma/SKILL.md': '---\nname: gamma\ndescription: Use when testing a skill that only has a Codex copy.\n---\n\nGamma body.\n',
    '.agents/skills/delta/SKILL.md': ADAPTER,
    '.claude/skills/mismatch/SKILL.md': '---\nname: other-name\ndescription: Use when testing a frontmatter name that differs from its folder.\n---\n',
    '.claude/skills/linky/SKILL.md': '---\nname: linky\ndescription: Use when testing a relative link to a file the bundle lacks.\n---\n\nSee [missing](references/missing.md).\n',
    '.claude/skills/PROVENANCE.md': '# Provenance\n\nNot a skill.\n',
  };
  for (const [file, text] of Object.entries(files)) await put(seed, file, text);
  await commit(seed, 'skills');
  const remote = path.join(temp, 'remote.git'); await run('git', ['clone', '-q', '--bare', seed, remote]);
  const root = path.join(temp, 'CoreWise'); await mkdir(root);
  const source = path.join(root, 'Harness-Firmware'); await run('git', ['clone', '-q', remote, source]);
  await writeFile(path.join(source, '.claude/skills/alpha/SKILL.md'), 'uncommitted edit\n');
  const dest = path.join(temp, 'dsh', 'skills'); await mkdir(dest, { recursive: true });
  // A hand-installed gamma that differs from the source.
  await put(dest, 'gamma/SKILL.md', '---\nname: gamma\ndescription: Use when testing a hand-installed copy that differs.\n---\n\nHand copy.\n');
  const options = { source, dest, modules: MODULES, record: path.join(temp, 'record.json') };
  const install = { dest, modules: MODULES, record: options.record, staging: path.join(temp, 'dsh', '.corewise-staging'), backups: path.join(temp, 'backups') };
  return { temp, seed, remote, source, dest, options, install };
}
const byName = preview => Object.fromEntries(preview.skills.map(skill => [skill.name, skill]));

test('frontmatter adaptation only touches what DSH needs', () => {
  const plain = '---\nname: a\ndescription: Use when x.\n---\nbody\n';
  assert.deepEqual(adaptFrontmatter(plain, { folder: 'a' }), { text: plain, rewrites: [] });
  const named = adaptFrontmatter('---\ndescription: Use when x.\n---\nbody: with colon\n', { folder: 'b' });
  assert.equal(named.text, '---\nname: b\ndescription: Use when x.\n---\nbody: with colon\n');
  const legacy = adaptFrontmatter('---\nname: c\ndescription: d\nuserInvocable: false\nmodelInvocable: false\n---\n');
  assert.match(legacy.text, /\nuser-invocable: false\ndisable-model-invocation: true\n/);
  assert.equal(adaptFrontmatter('---\nname: d\ndescription: Use for x: y\n---\n', { quote: true }).text, '---\nname: d\ndescription: "Use for x: y"\n---\n');
  assert.equal(adaptFrontmatter('no frontmatter').rewrites.length, 0);
});

test('link check separates broken links from outside paths', () => {
  const file = (p, text) => ({ path: p, data: Buffer.from(text) });
  const result = checkLinks([file('SKILL.md', '[a](references/a.md) [b](references/b.md) `scripts/x.mjs` `.claude/reference/p.md` [web](https://x.test) [up](../other/SKILL.md)'), file('references/a.md', '[back](../SKILL.md)'), file('scripts/y.mjs', '')]);
  assert.deepEqual(result.broken.sort(), ['SKILL.md: references/b.md', 'SKILL.md: scripts/x.mjs']);
  assert.deepEqual(result.outside.sort(), ['../other/SKILL.md', '.claude/reference/p.md']);
});

test('secrets, caches and keys are never copied', () => {
  assert.match(skipReason('.env'), /secrets/);
  assert.match(skipReason('config/settings.local.json'), /secrets/);
  assert.match(skipReason('node_modules/x/index.js'), /transient/);
  assert.match(skipReason('notes.txt', Buffer.from('-----BEGIN RSA PRIVATE KEY-----')), /private key/);
  assert.equal(skipReason('references/guide.md', Buffer.from('ok')), null);
});

test('preview reads origin/main, validates with the DSH parser, and classifies each skill', { skip: !haveDsh && 'DSH is not installed' }, async t => {
  const data = await fixture(t);
  const preview = await previewDsh(data.options);
  const skills = byName(preview);
  assert.equal(preview.source.commit, (await run('git', ['--git-dir', data.remote, 'rev-parse', 'main'])).trim());
  assert.deepEqual(Object.keys(skills).sort(), ['alpha', 'beta', 'gamma', 'linky', 'mismatch']);
  assert.equal(skills.alpha.status, 'new');
  assert.deepEqual(skills.alpha.files.sort(), ['SKILL.md', 'references/guide.md', 'scripts/run.mjs']);
  assert.deepEqual(skills.alpha.skipped.map(item => item.path).sort(), ['.env', 'node_modules/dep/index.js']);
  assert.match(skills.alpha.notes.join(), /\.claude\/reference\/pitfalls\.md/);
  assert.equal(skills.beta.status, 'new');
  assert.match(skills.beta.notes.join(), /name: beta added/);
  assert.match(skills.beta.notes.join(), /quoted for YAML/);
  assert.match(skills.beta.notes.join(), /\$ARGUMENTS/);
  assert.equal(skills.gamma.layout, '.agents/skills');
  assert.equal(skills.gamma.status, 'conflict');
  assert.equal(skills.mismatch.status, 'invalid');
  assert.match(skills.mismatch.errors.join(), /does not match folder/);
  assert.equal(skills.linky.status, 'invalid');
  assert.match(skills.linky.errors.join(), /broken relative link/);
  assert.equal((await readdir(data.dest)).join(), 'gamma');
});

test('install stages, verifies with DSH discovery, backs up a changed copy, and records it', { skip: !haveDsh && 'DSH is not installed' }, async t => {
  const data = await fixture(t);
  const preview = await previewDsh(data.options);
  const log = [];
  const results = await installDsh({ preview, choices: [{ name: 'alpha', policy: 'install' }, { name: 'beta', policy: 'install' }, { name: 'gamma', policy: 'backup' }, { name: 'mismatch', policy: 'install' }], ...data.install, onOutput: text => log.push(text) });
  const result = Object.fromEntries(results.map(item => [item.name, item]));
  assert.equal(result.alpha.result, 'installed');
  assert.equal(result.alpha.path, path.join(data.dest, 'alpha'));
  assert.deepEqual(result.alpha.verified, { files: 3, frontmatter: true, links: true, discovered: true });
  assert.equal(result.mismatch.result, 'skipped');
  assert.equal(await readFile(path.join(data.dest, 'alpha/references/guide.md'), 'utf8'), 'Guide. Back to [the skill](../SKILL.md).\n');
  await assert.rejects(access(path.join(data.dest, 'alpha/.env')));
  assert.match(await readFile(path.join(data.dest, 'beta/SKILL.md'), 'utf8'), /^---\nname: beta\ndescription: "Use when testing: a colon inside a plain description."\n---/);
  assert.equal(result.gamma.result, 'updated');
  assert.match(await readFile(path.join(result.gamma.backup, 'gamma', 'SKILL.md'), 'utf8'), /Hand copy/);
  assert.match(await readFile(path.join(data.dest, 'gamma/SKILL.md'), 'utf8'), /Gamma body/);
  const discovered = await (await loadDiscovery(MODULES))(data.dest);
  assert.deepEqual(discovered.skills.map(skill => skill.name).sort(), ['alpha', 'beta', 'gamma']);
  assert.deepEqual(discovered.warnings, []);
  const record = JSON.parse(await readFile(data.options.record, 'utf8'));
  assert.deepEqual(Object.keys(record.roots[path.resolve(data.dest).toLowerCase()]).sort(), ['alpha', 'beta', 'gamma']);
  await assert.rejects(access(data.install.staging));
  assert.match(log.join(''), /Done\. 3 installed or updated, 1 skipped, 0 failed/);

  // A new source commit reaches DSH as an update of the recorded copy, no policy needed.
  await put(data.seed, '.claude/skills/alpha/references/guide.md', 'Guide v2.\n');
  await commit(data.seed, 'alpha v2');
  await run('git', ['-C', data.seed, 'push', '-q', data.remote, 'main']);
  const next = byName(await previewDsh(data.options));
  assert.equal(next.alpha.status, 'update');
  assert.deepEqual(next.alpha.changes, { added: [], changed: ['references/guide.md'], removed: [] });
  assert.equal(next.beta.status, 'current');
  const [updated] = await installDsh({ preview: { source: { commit: 'x' }, skills: [next.alpha] }, choices: [{ name: 'alpha', policy: 'install' }], ...data.install });
  assert.equal(updated.result, 'updated');
  assert.equal(await readFile(path.join(data.dest, 'alpha/references/guide.md'), 'utf8'), 'Guide v2.\n');
});

test('a changed DSH copy is never overwritten without a policy or after the preview', { skip: !haveDsh && 'DSH is not installed' }, async t => {
  const data = await fixture(t);
  const preview = await previewDsh(data.options);
  const [skipped] = await installDsh({ preview, choices: [{ name: 'gamma', policy: 'install' }], ...data.install });
  assert.equal(skipped.result, 'skipped');
  await writeFile(path.join(data.dest, 'gamma/SKILL.md'), '---\nname: gamma\ndescription: Use when testing an edit made after the preview.\n---\n');
  const [late] = await installDsh({ preview, choices: [{ name: 'gamma', policy: 'replace' }], ...data.install });
  assert.equal(late.result, 'skipped');
  assert.match(late.error, /changed after the preview/);
  assert.match(await readFile(path.join(data.dest, 'gamma/SKILL.md'), 'utf8'), /after the preview/);
});

test('a failed install rolls back and leaves the previous copy in place', { skip: !haveDsh && 'DSH is not installed' }, async t => {
  const data = await fixture(t);
  const preview = await previewDsh(data.options);
  const gamma = preview.skills.find(skill => skill.name === 'gamma');
  // A preview whose recorded hash no longer matches its bytes fails the in-place check.
  await assert.rejects(installDsh({ preview: { ...preview, skills: [{ ...gamma, hash: 'tampered' }] }, choices: [{ name: 'gamma', policy: 'replace' }], ...data.install }), /1 of 1 skills failed/);
  assert.match(await readFile(path.join(data.dest, 'gamma/SKILL.md'), 'utf8'), /Hand copy/);
  assert.deepEqual(await readdir(data.dest), ['gamma']);
  await assert.rejects(access(data.options.record));
});

test('compare shows the DSH copy against the incoming copy', { skip: !haveDsh && 'DSH is not installed' }, async t => {
  const data = await fixture(t);
  const gamma = (await previewDsh(data.options)).skills.find(skill => skill.name === 'gamma');
  const diff = await compareDsh({ skill: gamma, dest: data.dest });
  assert.match(diff, /--- a\/dsh\/gamma\/SKILL\.md/);
  assert.match(diff, /\+\+\+ b\/incoming\/gamma\/SKILL\.md/);
  assert.match(diff, /-Hand copy\./);
  assert.match(diff, /\+Gamma body\./);
});

test('an edit to a flat copy beside the folder after the preview blocks the install', { skip: !haveDsh && 'DSH is not installed' }, async t => {
  const data = await fixture(t);
  await put(data.dest, 'gamma.md', '---\nname: gamma\ndescription: Use when testing a flat copy beside the folder.\n---\n');
  const preview = await previewDsh(data.options);
  await writeFile(path.join(data.dest, 'gamma.md'), '---\nname: gamma\ndescription: Use when testing a flat copy edited after the preview.\n---\n');
  const [late] = await installDsh({ preview, choices: [{ name: 'gamma', policy: 'replace' }], ...data.install });
  assert.equal(late.result, 'skipped');
  assert.match(await readFile(path.join(data.dest, 'gamma.md'), 'utf8'), /edited after the preview/);
});

test('compare also shows a flat copy the install would move aside', { skip: !haveDsh && 'DSH is not installed' }, async t => {
  const data = await fixture(t);
  await put(data.dest, 'gamma.md', '---\nname: gamma\ndescription: Flat gamma copy that sits beside the folder.\n---\nFlat copy.\n');
  const gamma = (await previewDsh(data.options)).skills.find(skill => skill.name === 'gamma');
  const diff = await compareDsh({ skill: gamma, dest: data.dest });
  assert.match(diff, /--- a\/dsh\/gamma\.md/);
  assert.match(diff, /-Flat copy\./);
});
