import { createHash, randomBytes } from 'node:crypto';
import { spawn } from 'node:child_process';
import { access, cp, lstat, mkdir, mkdtemp, readdir, readFile, rename, rm, rmdir, writeFile } from 'node:fs/promises';
import { homedir, tmpdir } from 'node:os';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { run } from './core.mjs';
import { GIT_CRED, parseTree, readBlobs } from './sync.mjs';

// DSH skill install: ports skill bundles from the Harness-Firmware checkout into the DSH global
// skill root. The source is the checkout's origin/main commit, read from git objects, so dirty,
// untracked and ignored files in the working folder never travel. Validation and the final
// discovery check run DSH's own filesystem skill provider, so "valid" means what DSH loads.

const DSH_HOME = process.env.DSH_HOME ? path.resolve(process.env.DSH_HOME) : path.join(homedir(), '.dsh');
export const DSH_DEFAULTS = {
  dest: path.join(DSH_HOME, 'skills'),
  // Staging sits beside the skill root (same volume, so a swap is a rename) but outside it, so
  // DSH's watcher never sees a half-written bundle.
  staging: path.join(DSH_HOME, '.corewise-staging'),
  modules: path.join(DSH_HOME, 'profiles', 'node_modules'),
  record: path.join(homedir(), '.corewise-cloner', 'dsh-installs.json'),
  backups: path.join(homedir(), '.corewise-cloner', 'dsh-backups'),
};

// Source layouts in preference order. .claude/skills is the canonical copy in Harness repositories;
// .agents/skills holds Codex copies, used only for skills with no Claude copy.
const LAYOUTS = ['.dsh/skills', '.claude/skills', '.agents/skills', '.codex/skills', 'skills'];
const ADAPTER_MARKER = '<!-- Generated by .claude/scripts/sync-codex-skills.mjs. Do not edit. -->';
const SKILL_NAME = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const DIR_NAME = /^[A-Za-z0-9_-]+$/;
const SKIP_DIRS = new Set(['node_modules', '.git', '.tmp', '__pycache__', '.venv', '.pytest_cache', '.cache']);
const SKIP_FILES = /^(\.env(\..*)?|\.DS_Store|Thumbs\.db|desktop\.ini|id_(rsa|dsa|ecdsa|ed25519)(\.pub)?|\.credentials.*|.*\.(pem|key|p12|pfx|log|pyc)|.*\.local\.json)$/i;
const PRIVATE_KEY = /-----BEGIN [A-Z ]*PRIVATE KEY-----/;
const exists = target => access(target).then(() => true, () => false);
const sha = data => createHash('sha256').update(data).digest('hex');
// Folder identity: sorted relative paths with content hashes.
const bundleHash = files => sha([...files].sort((a, b) => a.path.localeCompare(b.path)).map(file => `${file.path}\0${sha(file.data)}\n`).join(''));

// Files a bundle must not carry: secrets, caches and generated output. Reported, never copied.
export function skipReason(relative, data) {
  const parts = relative.split('/');
  const dir = parts.slice(0, -1).find(part => SKIP_DIRS.has(part));
  if (dir) return `${dir} folder is transient`;
  if (SKIP_FILES.test(parts.at(-1))) return 'may hold secrets or generated output';
  if (data && data.length < 1_000_000 && PRIVATE_KEY.test(data.toString('latin1'))) return 'contains a private key';
  return null;
}

// Loads DSH's own skill provider from the DSH install, so checks follow the installed parser.
export async function loadDiscovery(modules = DSH_DEFAULTS.modules) {
  const entry = path.join(modules, '@deepseek-ai', 'dsh-skill-filesystem', 'lib', 'index.js');
  if (!await exists(entry)) throw new Error(`DSH skill parser not found at ${entry}. Start DSH once so its profile packages are installed.`);
  const { FileSystemSkillProvider } = await import(pathToFileURL(entry).href);
  // Lists the skills DSH would discover in one root, plus the warnings it logs for skipped entries.
  return async root => {
    const warnings = [];
    const logger = { warn: message => warnings.push(String(message)), error: message => warnings.push(String(message)), info() {}, debug() {} };
    const provider = new FileSystemSkillProvider({ get: () => undefined, logger }, { invalidate() {}, signal: new AbortController().signal }, { includeDefaultRoots: false, customSkillDirs: [root], watch: false });
    const skills = (await provider.list({ cwd: root })).map(skill => ({ name: skill.name, description: skill.description, invocation: skill.invocation, path: skill.path }));
    return { skills, warnings };
  };
}

// Frontmatter text between the fences, or null. Same fence rules as DSH.
function frontmatter(text) {
  const lines = text.split('\n');
  if (lines[0].replace(/\r$/, '') !== '---') return null;
  const end = lines.findIndex((line, index) => index > 0 && line.replace(/\r$/, '') === '---');
  if (end < 0) return null;
  return { head: lines.slice(1, end), end, lines };
}
const BOOL = { true: true, yes: true, on: true, 1: true, false: false, no: false, off: false, 0: false };

// Frontmatter rewrites DSH needs to load a skill at all, and nothing else. The body stays as written.
// - camelCase invocation keys (Claude Code tolerates them; DSH drops the whole skill)
// - a plain scalar holding ": " or " #" (lenient parsers accept it; DSH's YAML parser rejects it)
// - a missing name (Claude Code takes the folder name; DSH requires the field)
export function adaptFrontmatter(text, { quote = false, folder = null } = {}) {
  const found = frontmatter(text); if (!found) return { text, rewrites: [] };
  const rewrites = [];
  const addName = folder && SKILL_NAME.test(folder) && !found.head.some(line => /^name\s*:/.test(line));
  if (addName) rewrites.push(`name: ${folder} added from the folder name`);
  const head = found.head.map(line => {
    const match = /^([A-Za-z][A-Za-z0-9_-]*):(\s*)(.*?)(\r?)$/.exec(line); if (!match) return line;
    let [, key, gap, value, cr] = match;
    const flag = BOOL[value.replace(/^["']|["']$/g, '').toLowerCase()];
    if (key === 'disableModelInvocation' || key === 'userInvocable') {
      const next = key === 'userInvocable' ? 'user-invocable' : 'disable-model-invocation';
      rewrites.push(`${key} renamed to ${next}`); key = next;
    } else if (key === 'modelInvocable' && flag !== undefined) {
      rewrites.push(`modelInvocable: ${value} rewritten as disable-model-invocation: ${!flag}`); key = 'disable-model-invocation'; value = String(!flag);
    }
    if (quote && value && !/^["'[{|>&*!#]/.test(value) && /: |\s#/.test(value)) { rewrites.push(`${key} value quoted for YAML`); value = JSON.stringify(value); }
    return `${key}:${gap || ' '}${value}${cr}`;
  });
  if (!rewrites.length) return { text, rewrites };
  const name = addName ? [`name: ${folder}${found.lines[0].endsWith('\r') ? '\r' : ''}`] : [];
  return { text: [found.lines[0], ...name, ...head, ...found.lines.slice(found.end)].join('\n'), rewrites };
}

// Relative links and bundle paths named in the bundle's Markdown: those inside the bundle must
// exist; those pointing outside it are reported, since only the bundle is installed.
export function checkLinks(files) {
  const have = new Set(files.map(file => file.path));
  const dirs = new Set(files.flatMap(file => file.path.split('/').slice(0, -1).map((_, index, parts) => parts.slice(0, index + 1).join('/'))));
  const tops = new Set(files.map(file => file.path.split('/')[0]));
  const broken = new Set(), outside = new Set();
  for (const file of files.filter(file => file.path.endsWith('.md'))) {
    const text = file.data.toString('utf8'), base = path.posix.dirname(file.path);
    const targets = [];
    for (const match of text.matchAll(/\]\(([^)\s]+)(?:\s+"[^"]*")?\)/g)) targets.push({ raw: match[1], link: true });
    for (const match of text.matchAll(/`([^`\s]+)`/g)) targets.push({ raw: match[1], link: false });
    for (const { raw, link } of targets) {
      if (/^[a-z][a-z0-9+.-]*:/i.test(raw) || raw.startsWith('#') || raw.includes('*') || raw.includes('<') || raw.includes('$')) continue;
      let target; try { target = decodeURI(raw.split('#')[0]).replace(/\/$/, ''); } catch { continue; }
      if (!target) continue;
      if (!link) {
        // A backticked token counts only when it names something the bundle ships or a repository folder.
        if (/^\.(claude|agents|codex|dsh)\//.test(target)) { outside.add(target); continue; }
        if (!target.includes('/') || !tops.has(target.split('/')[0])) continue;
      }
      if (path.posix.isAbsolute(target) || /^[A-Za-z]:/.test(target)) { outside.add(target); continue; }
      const resolved = path.posix.normalize(path.posix.join(link ? base : '.', target));
      if (resolved.startsWith('..')) outside.add(target);
      else if (!have.has(resolved) && !dirs.has(resolved)) broken.add(`${file.path}: ${target}`);
    }
  }
  return { broken: [...broken], outside: [...outside] };
}

async function treeFiles(dir, base = dir) {
  const files = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) files.push(...await treeFiles(full, base));
    else files.push({ path: path.relative(base, full).split(path.sep).join('/'), data: entry.isFile() ? await readFile(full) : Buffer.from(`<${entry.isSymbolicLink() ? 'symlink' : 'special'}>`) });
  }
  return files;
}
async function writeBundle(dir, files) {
  for (const file of files) { const target = path.join(dir, ...file.path.split('/')); await mkdir(path.dirname(target), { recursive: true }); await writeFile(target, file.data); }
}
// Windows can hold a folder briefly (indexer, antivirus, DSH's watcher), so a rename retries.
async function move(from, to) {
  for (let attempt = 0; ; attempt++) {
    try { return await rename(from, to); }
    catch (error) {
      if (error.code === 'EXDEV') { await cp(from, to, { recursive: true }); return rm(from, { recursive: true, force: true }); }
      if (attempt >= 5 || !['EPERM', 'EBUSY', 'EACCES'].includes(error.code)) throw error;
      await new Promise(resolve => setTimeout(resolve, 150 * (attempt + 1)));
    }
  }
}
// Install record, one entry per destination root and skill, so two roots never vouch for each other.
const readRecord = async file => { try { const data = JSON.parse(await readFile(file, 'utf8')); data.roots ??= {}; return data; } catch { return { version: 1, roots: {} }; } };
const rootKey = dest => path.resolve(dest).toLowerCase();
async function writeRecord(file, data) { await mkdir(path.dirname(file), { recursive: true }); const temp = `${file}.${randomBytes(4).toString('hex')}.tmp`; await writeFile(temp, `${JSON.stringify(data, null, 2)}\n`); await move(temp, file); }

// Skill bundles in the checkout at origin/main (after a fetch), one per folder name, best layout first.
export async function readSource({ source, execute = run, fetch = true }) {
  const git = args => execute('git', ['-C', source, ...args]);
  if (!await exists(path.join(source, '.git'))) throw new Error(`No Git checkout at ${source}.`);
  let refreshed = false, note = null;
  if (fetch) await git([...GIT_CRED, 'fetch', '--quiet', 'origin', 'main']).then(() => { refreshed = true; }, error => { note = `Could not fetch origin/main; using the last fetched copy. ${String(error.message).split('\n')[0]}`; });
  const commit = (await git(['rev-parse', 'origin/main'])).trim();
  const gitDir = path.resolve(source, (await git(['rev-parse', '--git-common-dir'])).trim());
  const entries = parseTree(await git(['ls-tree', '-r', '-z', '--full-tree', commit, '--', ...LAYOUTS.map(layout => `${layout}/`)]));
  const candidates = new Map();
  for (const layout of LAYOUTS) {
    const mine = entries.filter(entry => entry.path.startsWith(`${layout}/`) && !LAYOUTS.some(other => other !== layout && other.startsWith(`${layout}/`) && entry.path.startsWith(`${other}/`)));
    const folders = new Map();
    for (const entry of mine) {
      const rest = entry.path.slice(layout.length + 1); const slash = rest.indexOf('/');
      if (slash < 0) { if (rest.endsWith('.md') && rest !== 'SKILL.md') folders.set(rest.slice(0, -3), { flat: entry, entries: [] }); continue; }
      const name = rest.slice(0, slash);
      if (!folders.has(name) || folders.get(name).flat) folders.set(name, { flat: null, entries: [] });
      folders.get(name).entries.push({ ...entry, relative: rest.slice(slash + 1) });
    }
    for (const [name, found] of folders) {
      if (candidates.has(name) || !DIR_NAME.test(name)) continue;
      if (!found.flat && !found.entries.some(entry => entry.relative === 'SKILL.md')) continue;
      candidates.set(name, { name, layout, flat: Boolean(found.flat), entries: found.flat ? [{ ...found.flat, relative: 'SKILL.md' }] : found.entries });
    }
  }
  const wanted = [...new Set([...candidates.values()].flatMap(item => item.entries.filter(entry => entry.type === 'blob' && entry.mode !== '120000').map(entry => entry.sha)))];
  const blobs = wanted.length ? await readBlobs(gitDir, wanted) : new Map();
  const bundles = [];
  for (const item of candidates.values()) {
    const skill = blobs.get(item.entries.find(entry => entry.relative === 'SKILL.md')?.sha);
    const text = skill?.toString('utf8') ?? '';
    // A Markdown file with no frontmatter (PROVENANCE.md, a README) is not a skill; a generated
    // Codex adapter only points back at the Claude copy, so it cannot stand alone.
    if (item.flat && !text.startsWith('---')) continue;
    if (text.includes(ADAPTER_MARKER) && item.entries.length === 1) continue;
    const files = [], skipped = [];
    for (const entry of item.entries) {
      if (entry.type !== 'blob' || entry.mode === '120000') { skipped.push({ path: entry.relative, reason: entry.mode === '120000' ? 'symbolic link' : 'submodule' }); continue; }
      const data = blobs.get(entry.sha), reason = skipReason(entry.relative, data);
      if (reason) skipped.push({ path: entry.relative, reason }); else files.push({ path: entry.relative, data, mode: entry.mode });
    }
    const alternates = LAYOUTS.filter(layout => layout !== item.layout && entries.some(entry => entry.path.startsWith(`${layout}/${item.name}/SKILL.md`)));
    bundles.push({ name: item.name, layout: item.layout, flat: item.flat, sourcePath: item.flat ? `${item.layout}/${item.name}.md` : `${item.layout}/${item.name}`, alternates, files, skipped });
  }
  return { source, commit, refreshed, note, bundles: bundles.sort((a, b) => a.name.localeCompare(b.name)) };
}

// Destination state of one folder name: a bundle folder, a flat <name>.md, or nothing.
async function destState(dest, name) {
  const dir = path.join(dest, name), flat = path.join(dest, `${name}.md`);
  const info = await lstat(dir).catch(() => null), flatInfo = await lstat(flat).catch(() => null);
  // A flat <name>.md beside the folder is part of the state: an install moves both aside.
  const flatHash = flatInfo ? sha(await readFile(flat).catch(() => Buffer.alloc(0))) : null;
  const withFlat = hash => flatHash ? sha(`${hash}\0${flatHash}`) : hash;
  if (info?.isDirectory()) { const files = await treeFiles(dir); return { kind: 'dir', path: dir, files, hash: withFlat(bundleHash(files)), flat: flatInfo ? flat : null }; }
  if (info) return { kind: 'file', path: dir, hash: withFlat(sha(await readFile(dir).catch(() => Buffer.alloc(0)))), flat: flatInfo ? flat : null };
  if (flatInfo) return { kind: 'flat', path: flat, hash: flatHash, flat };
  return null;
}
const fileChanges = (ours, theirs) => {
  const mine = new Map(ours.map(file => [file.path, sha(file.data)])), other = new Map((theirs ?? []).map(file => [file.path, sha(file.data)]));
  return { added: [...mine.keys()].filter(file => !other.has(file)), changed: [...mine.keys()].filter(file => other.has(file) && other.get(file) !== mine.get(file)), removed: [...other.keys()].filter(file => !mine.has(file)) };
};

// Renders every source bundle for DSH, validates it with DSH's parser, and classifies it against
// the destination. Nothing under dest changes.
export async function previewDsh({ source, dest = DSH_DEFAULTS.dest, modules = DSH_DEFAULTS.modules, record = DSH_DEFAULTS.record, execute = run, fetch = true }) {
  const discover = await loadDiscovery(modules);
  const read = await readSource({ source, execute, fetch });
  const installed = (await readRecord(record)).roots[rootKey(dest)] ?? {};
  const scratch = await mkdtemp(path.join(tmpdir(), 'corewise-dsh-'));
  try {
    // Each bundle is rendered under its folder name, as it would sit in the DSH root.
    const rendered = new Map();
    for (const bundle of read.bundles) {
      const files = bundle.files.map(file => ({ ...file }));
      const main = files.find(file => file.path === 'SKILL.md');
      if (!main) { rendered.set(bundle.name, { files, rewrites: [] }); continue; }
      const adapted = adaptFrontmatter(main.data.toString('utf8'), { folder: bundle.name });
      main.data = Buffer.from(adapted.text); rendered.set(bundle.name, { files, rewrites: adapted.rewrites });
      await writeBundle(path.join(scratch, bundle.name), files);
    }
    let found = await discover(scratch);
    // A YAML failure gets one more try with plain scalars quoted; kept only if DSH then loads it.
    for (const bundle of read.bundles) {
      const file = path.join(scratch, bundle.name, 'SKILL.md');
      if (!found.warnings.some(warning => warning.includes(file) && warning.includes('invalid YAML'))) continue;
      const item = rendered.get(bundle.name), main = item.files.find(entry => entry.path === 'SKILL.md');
      if (!main) continue;
      const quoted = adaptFrontmatter(main.data.toString('utf8'), { quote: true, folder: bundle.name });
      if (!quoted.rewrites.length) continue;
      await writeFile(file, quoted.text);
      const retry = await discover(scratch);
      if (retry.skills.some(skill => skill.path === file)) { main.data = Buffer.from(quoted.text); item.rewrites = [...new Set([...item.rewrites, ...quoted.rewrites])]; found = retry; }
      else await writeFile(file, main.data);
    }
    const destFound = await discover(dest).catch(error => ({ skills: [], warnings: [`Could not scan ${dest}: ${error.message}`] }));
    const skills = [];
    for (const bundle of read.bundles) {
      const { files, rewrites } = rendered.get(bundle.name);
      const file = path.join(scratch, bundle.name, 'SKILL.md');
      const seen = found.skills.find(skill => skill.path === file);
      const errors = found.warnings.filter(warning => warning.includes(file)).map(warning => warning.replace(`skill file ${file} ignored: `, '').split('\n')[0]);
      const warnings = [], notes = [];
      const main = files.find(entry => entry.path === 'SKILL.md');
      if (!main) errors.push('SKILL.md is not a regular file in the source');
      else if (!seen && !errors.length) errors.push('DSH does not discover this bundle');
      if (seen) {
        if (seen.name !== bundle.name) errors.push(`frontmatter name "${seen.name}" does not match folder "${bundle.name}"`);
        const text = seen.description.replace(/\s+/g, ' ').trim();
        if (text.length > 500) warnings.push(`description is ${text.length} characters; DSH shows the first 497 in its catalog`);
        if (text.length < 20) warnings.push('description is too short for DSH to route requests to this skill');
        if (!seen.invocation.userInvocable) notes.push('model only: user-invocable is false in the source, so there is no /name command');
        if (!seen.invocation.modelInvocable) notes.push('human only: disable-model-invocation is true in the source');
        const other = destFound.skills.find(skill => skill.name === seen.name && path.dirname(skill.path) !== path.join(dest, bundle.name) && skill.path !== path.join(dest, `${bundle.name}.md`));
        if (other) errors.push(`another DSH skill already uses the name "${seen.name}" at ${other.path}`);
      }
      const head = main && frontmatter(main.data.toString('utf8'));
      if (head && head.head.join('\n').length > 1024) warnings.push(`frontmatter is ${head.head.join('\n').length} characters; keep it under 1024`);
      const links = checkLinks(files);
      for (const link of links.broken) errors.push(`broken relative link ${link}`);
      // A path into another skill's folder is a dependency on that skill; any other outside path is
      // read from the active project at run time and is not part of this bundle.
      const skillPath = /^\.(?:claude|agents|codex|dsh)\/skills\/([A-Za-z0-9_-]+)\//;
      const uses = [...new Set(links.outside.map(target => skillPath.exec(target)?.[1]).filter(other => other && other !== bundle.name))];
      const project = links.outside.filter(target => !skillPath.test(target));
      const known = new Set(read.bundles.map(item => item.name));
      if (uses.length) notes.push(`reads another skill's files: ${uses.map(other => known.has(other) ? other : `${other} (not in the source)`).join(', ')}. Inside a Harness repository the repository copy is used; elsewhere install ${uses.length === 1 ? 'it' : 'them'} too`);
      if (project.length) notes.push(`names project paths that stay in the active project and are not installed: ${project.slice(0, 5).join(', ')}${project.length > 5 ? ', ...' : ''}`);
      if (files.some(entry => entry.path.endsWith('.md') && /\$ARGUMENTS/.test(entry.data.toString('utf8')))) notes.push('mentions $ARGUMENTS, which Claude Code fills in; DSH leaves it as written and the request stays in the conversation');
      for (const rewrite of rewrites) notes.push(`rewritten for DSH: ${rewrite}`);
      const hash = bundleHash(files), destination = await destState(dest, bundle.name);
      let status, reason = null;
      if (errors.length) status = 'invalid';
      else if (!destination) status = 'new';
      else if (destination.kind === 'dir' && destination.hash === hash && !destination.flat) status = 'current';
      else if (destination.kind === 'dir' && !destination.flat && installed[bundle.name]?.hash === destination.hash) status = 'update';
      else { status = 'conflict'; reason = destination.kind !== 'dir' || destination.flat ? 'a flat or non-folder skill with this name exists in DSH' : installed[bundle.name] ? 'changed in DSH since Harness Console installed it' : 'installed by hand or by another tool'; }
      skills.push({ name: bundle.name, uses, sourcePath: bundle.sourcePath, layout: bundle.layout, alternates: bundle.alternates, status, reason, errors, warnings, notes, skipped: bundle.skipped, files: files.map(entry => entry.path), changes: destination?.kind === 'dir' ? fileChanges(files, destination.files) : null, hash, destHash: destination?.hash ?? null, destPath: path.join(dest, bundle.name), invocation: seen?.invocation ?? null, rendered: files });
    }
    const destProblems = destFound.warnings.map(warning => warning.split('\n')[0]);
    return { source: { folder: source, commit: read.commit, refreshed: read.refreshed, note: read.note }, dest, destProblems, skills };
  } finally { await rm(scratch, { recursive: true, force: true }); }
}

// Unified diff from the installed copy to the one Harness Console would install.
export async function compareDsh({ skill, dest = DSH_DEFAULTS.dest }) {
  const scratch = await mkdtemp(path.join(tmpdir(), 'corewise-dsh-compare-'));
  try {
    // Both sides are copied under short names, so the diff headers read dsh/... and incoming/....
    await writeBundle(path.join(scratch, 'incoming', skill.name), skill.rendered);
    const current = await destState(dest, skill.name);
    await mkdir(path.join(scratch, 'dsh'), { recursive: true });
    if (current) await cp(current.path, path.join(scratch, 'dsh', path.basename(current.path)), { recursive: true });
    return await new Promise((resolve, reject) => {
      const child = spawn('git', ['diff', '--no-index', '--no-color', '--', 'dsh', 'incoming'], { cwd: scratch, windowsHide: true, shell: false, stdio: ['ignore', 'pipe', 'pipe'] });
      let out = '', err = ''; child.stdout.on('data', data => { out += data; }); child.stderr.on('data', data => { err += data; });
      child.on('error', reject);
      child.on('close', code => code <= 1 ? resolve((out || 'No differences.\n').slice(0, 200_000)) : reject(new Error(err.trim() || `git diff exited with code ${code}`)));
    });
  } finally { await rm(scratch, { recursive: true, force: true }); }
}

// Installs chosen skills from a preview. choices: [{ name, policy: 'install' | 'backup' | 'replace' }].
// Each skill is staged, checked with DSH's parser, swapped in by rename and checked again in
// place; any failure puts the previous copy back, so a skill is either fully new or unchanged.
export async function installDsh({ preview, choices, dest = DSH_DEFAULTS.dest, staging = DSH_DEFAULTS.staging, backups = DSH_DEFAULTS.backups, modules = DSH_DEFAULTS.modules, record = DSH_DEFAULTS.record, onOutput = () => {} }) {
  const discover = await loadDiscovery(modules);
  const say = text => onOutput(`${text}\n`);
  const results = [];
  for (const { name, policy } of choices) {
    const skill = preview.skills.find(item => item.name === name);
    const done = (result, extra = {}) => { results.push({ name, result, ...extra }); say(`${name}: ${result}${extra.error ? `. ${extra.error}` : ''}${extra.path ? ` -> ${extra.path}` : ''}${extra.verified ? `; verified ${extra.verified.files} files, frontmatter, relative links and DSH discovery` : ''}${extra.backup ? `; previous copy in ${extra.backup}` : ''}`); };
    if (!skill) { done('skipped', { error: 'not in the preview' }); continue; }
    if (skill.status === 'invalid' || skill.status === 'current') { done('skipped', { error: `now ${skill.status}` }); continue; }
    if (skill.status === 'conflict' && !['backup', 'replace'].includes(policy)) { done('skipped', { error: 'changed in DSH; choose backup and update, or replace' }); continue; }
    const before = await destState(dest, name);
    if ((before?.hash ?? null) !== skill.destHash) { done('skipped', { error: 'the DSH copy changed after the preview; check again' }); continue; }
    const work = path.join(staging, `${name}-${randomBytes(4).toString('hex')}`);
    const target = path.join(dest, name), aside = [];
    let swapped = false;
    try {
      // 1. Stage and check the exact bytes the preview showed.
      const staged = path.join(work, 'next', name);
      await writeBundle(staged, skill.rendered);
      const check = await discover(path.join(work, 'next'));
      if (check.warnings.length || !check.skills.some(item => item.name === name)) throw new Error(`staged copy failed DSH validation: ${check.warnings[0] ?? 'not discovered'}`);
      // 2. Move whatever holds the name aside, then 3. rename the staged copy into place.
      await mkdir(path.join(work, 'previous'), { recursive: true });
      for (const old of [before?.path, before?.flat].filter((item, index, all) => item && all.indexOf(item) === index)) {
        const to = path.join(work, 'previous', path.basename(old)); await move(old, to); aside.push({ from: old, to });
      }
      await mkdir(dest, { recursive: true });
      await move(staged, target); swapped = true;
      // 4. Check in place: same bytes, relative links resolve, and DSH discovers it from the real root.
      const files = await treeFiles(target);
      if (bundleHash(files) !== skill.hash) throw new Error('installed files differ from the preview');
      const links = checkLinks(files); if (links.broken.length) throw new Error(`broken relative link ${links.broken[0]}`);
      const live = await discover(dest);
      const entry = live.skills.find(item => item.name === name);
      const problem = live.warnings.find(warning => warning.includes(path.join(target, 'SKILL.md')));
      if (problem || !entry || path.resolve(entry.path) !== path.resolve(target, 'SKILL.md')) throw new Error(`DSH does not discover it at ${target}: ${problem ?? (entry ? `the name resolves to ${entry.path}` : 'missing from the catalog')}`);
      const data = await readRecord(record); const mine = data.roots[rootKey(dest)] ??= {};
      mine[name] = { hash: skill.hash, commit: preview.source.commit, source: skill.sourcePath, installedAt: new Date().toISOString() };
      await writeRecord(record, data);
      // The install stands from here; a backup that cannot be moved stays in staging and is named.
      let backup = null;
      if (aside.length && policy === 'backup') {
        backup = path.join(backups, `${name}-${new Date().toISOString().replace(/[:.]/g, '-')}`);
        try { await mkdir(backup, { recursive: true }); for (const item of aside) await move(item.to, path.join(backup, path.basename(item.from))); }
        catch { backup = path.join(work, 'previous'); done(before ? 'updated' : 'installed', { path: target, files: files.length, backup, verified: { files: files.length, frontmatter: true, links: true, discovered: true } }); continue; }
      }
      done(before ? 'updated' : 'installed', { path: target, files: files.length, backup, verified: { files: files.length, frontmatter: true, links: true, discovered: true } });
    } catch (error) {
      // Roll back: remove the new copy and return the previous one.
      if (swapped) await rm(target, { recursive: true, force: true }).catch(() => {});
      let restored = true;
      for (const item of aside.reverse()) await move(item.to, item.from).catch(() => { restored = false; });
      done('failed', { error: `${error.message}. ${restored ? 'Nothing changed in DSH.' : `Could not restore the previous copy; it is in ${path.join(work, 'previous')}.`}` });
      if (!restored) continue;
    }
    await rm(work, { recursive: true, force: true }).catch(() => {});
  }
  await rmdir(staging).catch(() => {});
  const failed = results.filter(result => result.result === 'failed');
  say(`Done. ${results.filter(result => ['installed', 'updated'].includes(result.result)).length} installed or updated, ${results.filter(result => result.result === 'skipped').length} skipped, ${failed.length} failed.`);
  if (failed.length) throw Object.assign(new Error(`${failed.length} of ${results.length} skills failed: ${failed.map(result => result.name).join(', ')}`), { results });
  return results;
}

export function normalizeChoices(value) {
  if (!Array.isArray(value) || !value.length || value.length > 300) throw new Error('Choose skills to install.');
  const seen = new Set();
  return value.map(item => {
    if (!item || typeof item.name !== 'string' || !DIR_NAME.test(item.name)) throw new Error('Invalid skill name.');
    if (!['install', 'backup', 'replace'].includes(item.policy ?? 'install')) throw new Error('Invalid conflict policy.');
    if (seen.has(item.name)) throw new Error('Skill listed twice.'); seen.add(item.name);
    return { name: item.name, policy: item.policy ?? 'install' };
  });
}
