import { spawn } from 'node:child_process';
import { access, lstat, mkdir, mkdtemp, readdir, readFile, realpath, rm, writeFile } from 'node:fs/promises';
import { homedir, tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { run, validateRepo } from './core.mjs';
import { TEMPLATE } from './harness.mjs';

// Skill sync: compares every Harness repository cloned under root with the template's main and
// opens and squash-merges one pull request per repository with the selected skill updates. The commit
// goes to a new branch, harness-sync/<template sha7>, deleted after the merge. Status comes from git tree
// hashes: a local skill folder whose tree matches some past template version was never edited,
// so replacing it with the current version loses nothing. Anything else is left alone.
// Before committing, the repository's own checks run in a temporary worktree: sync-codex-skills.mjs
// --check and test-codex-contract.mjs (a check that passed on main and fails after the change stops
// that repository; one already failing on main is reported in the pull request) and removed-skills.mjs
// (warnings only). Paused repositories (the server passes them from the settings file; direct callers
// fall back to sync-skip.json), and repositories archived on GitHub, are
// shown with the reason and never written; a GitHub lookup that fails blocks the repository too.

export const GIT_CRED = ['-c', 'credential.helper=', '-c', 'credential.helper=!gh auth git-credential'];
const PARTS = ['.claude/skills', '.agents/skills'];
// skill-sources.json holds the reviewed hash of each native skill's Claude folder; the template's
// sync-codex-skills.mjs --check fails when a native skill's folder no longer matches its hash.
const SOURCES = '.agents/skill-sources.json';
const REGISTRIES = ['.agents/skill-modes.json', SOURCES];
// Each active skill sits in exactly one status row of this table. Older copies of
// test-codex-contract.mjs fail on a skill with no row (the template's current one only warns).
const COMPATIBILITY = '.agents/CODEX-SKILL-COMPATIBILITY.md';
const CLASS_ROW = /^\|\s*(Native|Adapted|Capability-gated|Dangerous|Claude-only)\s*\|(.*)\|\s*$/;
// skill -> status, from the table's rows.
export function classifications(text) {
  const found = new Map();
  for (const line of String(text).split(/\r?\n/)) { const match = CLASS_ROW.exec(line); if (match) for (const skill of match[2].matchAll(/`([^`]+)`/g)) found.set(skill[1], match[1]); }
  return found;
}
const PR_TITLE = 'Sync skills from Harness-Firmware';
// Skills a repository keeps as they are: a sync never updates, replaces or removes a locked skill.
// The list lives in the repository, so it travels with it: {"version": 1, "locks": {"<skill>": "<reason>"}}.
export const LOCKS = '.agents/skill-locks.json';
const LOCK_SHAPE = `${LOCKS}: expected {"version": 1, "locks": {"<skill>": "<reason>"}}`;
export function parseLocks(text) {
  let data; try { data = JSON.parse(text); } catch { throw new Error(LOCK_SHAPE); }
  if (data?.version !== 1 || !data.locks || typeof data.locks !== 'object' || Array.isArray(data.locks) || Object.entries(data.locks).some(([name, why]) => !SKILL_NAME.test(name) || typeof why !== 'string')) throw new Error(LOCK_SHAPE);
  return new Map(Object.entries(data.locks));
}
// A missing file locks nothing; one that cannot be read stops the repository instead of unlocking it.
async function readLocks(git, rev) {
  // ls-tree prints nothing for a missing path and fails only when git cannot read the tree.
  const present = (await git(['ls-tree', rev, '--', LOCKS])).trim() !== '';
  return present ? parseLocks(await git(['show', `${rev}:${LOCKS}`])) : new Map();
}
export const SKIP_FILE = fileURLToPath(new URL('./sync-skip.json', import.meta.url));
const SKILL_NAME = /^[A-Za-z0-9_-]+$/;
// Marks a Codex adapter the repository's own generator writes (and rebuilds); same test it uses.
const ADAPTER_MARKER = '<!-- Generated by .claude/scripts/sync-codex-skills.mjs. Do not edit. -->';
const exists = target => access(target).then(() => true, () => false);

export const TEMPLATE_CACHE = path.join(homedir(), '.corewise-cloner', 'harness-firmware.git');

// Reads many blobs through one `git cat-file --batch` process: "<sha> blob <size>\n<bytes>\n" each.
export function readBlobs(cache, shas) {
  return new Promise((resolve, reject) => {
    const child = spawn('git', ['--git-dir', cache, 'cat-file', '--batch'], { windowsHide: true, shell: false, stdio: ['pipe', 'pipe', 'pipe'] });
    const chunks = []; let stderr = '';
    child.stdout.on('data', data => chunks.push(data));
    child.stderr.on('data', data => { stderr += data; });
    child.on('error', reject);
    child.on('close', code => {
      if (code !== 0) return reject(new Error(stderr.trim() || `git cat-file exited with code ${code}`));
      const out = Buffer.concat(chunks), blobs = new Map(); let at = 0;
      while (at < out.length) {
        const newline = out.indexOf(10, at); const [sha, type, size] = out.subarray(at, newline).toString().split(' ');
        if (type !== 'blob') return reject(new Error(`Template object ${sha} is ${type ?? 'missing'}.`));
        blobs.set(sha, out.subarray(newline + 1, newline + 1 + Number(size))); at = newline + 2 + Number(size);
      }
      resolve(blobs);
    });
    child.stdin.end(shas.map(sha => `${sha}\n`).join(''));
  });
}
// A failed Node script's stderr starts with its stack location; the useful line names the error.
const reason = error => { const lines = String(error.message).split(/\r?\n/).map(line => line.trim()).filter(Boolean); return (lines.find(line => /^\w*Error:/.test(line)) ?? lines[0] ?? 'unknown error').replace(/^Error:\s*/, ''); };

// Repositories a sync must never write, such as a frozen take-home. The list ships with the app;
// one that cannot be read stops the sync instead of letting it write everywhere.
export async function readSkipList(file = SKIP_FILE) {
  const data = JSON.parse(await readFile(file, 'utf8'));
  if (data?.version !== 1 || !Array.isArray(data.skip) || data.skip.some(item => typeof item?.repo !== 'string' || typeof item.reason !== 'string')) {
    throw new Error(`${path.basename(file)}: expected {"version": 1, "skip": [{"repo": "owner/name", "reason": "..."}]}`);
  }
  const blank = data.skip.find(item => !item.reason.trim());
  if (blank) throw new Error(`${path.basename(file)}: the entry for ${JSON.stringify(blank.repo)} has an empty reason; say why the repository is never synced`);
  return data.skip;
}
// null when the repository is not listed. Callers test for null, not for an empty reason, so a
// listed repository stays skipped whatever its reason says.
export const skipReason = (skip, id) => { const item = skip.find(entry => entry.repo.toLowerCase() === id.toLowerCase()); return item ? item.reason : null; };

// What GitHub says about a repository before a sync writes to it. Archived: skipped. A failed or
// unclear answer blocks the repository rather than treating it as writable. The pull request goes
// to the name GitHub reports, which follows a rename the clone's origin may still use. The name is
// returned whenever GitHub gave one, so the skip list can match it even when the repository is
// archived or blocked.
async function githubState(id, execute) {
  let info;
  try { info = JSON.parse(await execute('gh', ['api', `repos/${id}`, '--jq', '{archived: .archived, name: .full_name, branch: .default_branch}'])); }
  catch (error) { return { blocked: `Could not check the repository on GitHub, so it cannot be synced. ${reason(error)}` }; }
  const name = typeof info?.name === 'string' ? info.name : undefined;
  if (info?.archived === true) return { skipped: 'Archived on GitHub', name };
  if (info?.archived !== false || !name) return { blocked: 'GitHub did not say whether the repository is archived, so it cannot be synced.' };
  if (info.branch !== 'main') return { blocked: `Its default branch on GitHub is ${info.branch}, not main; sync it by hand.`, name };
  return { name, branch: info.branch };
}

// `git ls-tree -z` rows: "<mode> <type> <sha>\t<path>".
export function parseTree(text) {
  return text.split('\0').filter(Boolean).map(row => {
    const tab = row.indexOf('\t'); const [mode, type, sha] = row.slice(0, tab).split(' ');
    return { mode, type, sha, path: row.slice(tab + 1) };
  });
}
// Skill folder tree hashes under both skill roots: { '.claude/skills': Map(name -> sha), ... }.
// A file, symlink or submodule at a skill path lands in odd ('<part>/<name>'): it is not a folder
// the template ever had, so treating it as absent would let a sync overwrite or delete it.
async function skillTrees(git, rev) {
  const trees = Object.fromEntries(PARTS.map(part => [part, new Map()])); trees.odd = new Set();
  for (const entry of parseTree(await git(['ls-tree', '-z', rev, ...PARTS.map(part => `${part}/`)]).catch(() => ''))) {
    const part = PARTS.find(prefix => entry.path.startsWith(`${prefix}/`)); const name = entry.path.slice(part.length + 1);
    if (!SKILL_NAME.test(name)) continue;
    if (entry.type === 'tree') trees[part].set(name, entry.sha); else trees.odd.add(`${part}/${name}`);
  }
  return trees;
}
const showJson = async (git, rev, file) => { try { return JSON.parse(await git(['show', `${rev}:${file}`])); } catch { return null; } };

const commitTrees = new Map();
// The template the last scan compared against; a compare reads the same head the page was shown.
let latestTemplate = null;
// Fetches the template into a private bare cache (trees only; blobs arrive when a skill is applied)
// and records every tree each skill folder has ever had on main.
export async function openTemplate({ cache = TEMPLATE_CACHE, source = `https://github.com/${TEMPLATE}.git`, execute = run, onOutput = () => {} } = {}) {
  const git = args => execute('git', ['--git-dir', cache, ...args]);
  if (!await exists(path.join(cache, 'HEAD'))) {
    onOutput('Caching the Harness-Firmware template…\n');
    await mkdir(path.dirname(cache), { recursive: true });
    await execute('git', [...GIT_CRED, 'clone', '--bare', '--quiet', '--filter=blob:none', '--config', 'credential.helper=', '--config', 'credential.helper=!gh auth git-credential', '--', source, cache]);
  } else {
    await git([...GIT_CRED, 'fetch', '--quiet', '--force', 'origin', '+refs/heads/main:refs/heads/main']);
  }
  const head = (await git(['rev-parse', 'refs/heads/main'])).trim();
  const history = Object.fromEntries(PARTS.map(part => [part, new Map()]));
  const commits = (await git(['log', '--format=%H', head, '--', ...PARTS])).split(/\r?\n/).filter(Boolean);
  for (let index = 0; index < commits.length; index += 8) {
    await Promise.all(commits.slice(index, index + 8).map(async commit => { if (!commitTrees.has(commit)) commitTrees.set(commit, await skillTrees(git, commit)); }));
  }
  // age: how recent each tree is, as the index of the newest commit holding it (0 = head).
  const age = Object.fromEntries(PARTS.map(part => [part, new Map()]));
  commits.forEach((commit, index) => { for (const part of PARTS) for (const [name, sha] of commitTrees.get(commit)[part]) {
    if (!history[part].has(name)) { history[part].set(name, new Set()); age[part].set(name, new Map()); }
    history[part].get(name).add(sha);
    if (!age[part].get(name).has(sha)) age[part].get(name).set(sha, index);
  } });
  const modes = (await showJson(git, head, '.agents/skill-modes.json'))?.skills ?? {};
  const registries = Object.fromEntries(await Promise.all(REGISTRIES.map(async file => [file, await showJson(git, head, file)])));
  const classes = classifications(await git(['show', `${head}:${COMPATIBILITY}`]).catch(() => ''));
  const current = await skillTrees(git, head);
  // Codex-only skills: a SKILL.md under .agents/skills with no Claude copy. A leftover folder without
  // SKILL.md is not a skill.
  const codexOnly = new Set((await git(['ls-tree', '-r', '-z', '--name-only', head, '--', `${PARTS[1]}/`])).split('\0')
    .map(file => /^\.agents\/skills\/([A-Za-z0-9_-]+)\/SKILL\.md$/.exec(file)?.[1]).filter(name => name && !current[PARTS[0]].has(name)));
  latestTemplate = { cache, head, git, current, codexOnly, history, age, modes, registries, classes, blobs: new Map() };
  return latestTemplate;
}

// Only real GitHub remotes: https (userinfo allowed), scp-style git@, or ssh://git@. Anchoring the
// host keeps look-alikes (notgithub.com, github.com.evil.test, a path containing github.com) out.
const GITHUB_URLS = [
  // Userinfo is limited to RFC 3986 characters: '#', '?' or '\' before '@' end the authority, so
  // git would connect to the host written before them, not github.com.
  /^https:\/\/(?:[A-Za-z0-9._~%!$&'()*+,;=:-]+@)?github\.com\/([^/\s]+\/[^/\s]+?)(?:\.git)?\/?$/i,
  /^git@github\.com:([^/\s]+\/[^/\s]+?)(?:\.git)?\/?$/i,
  /^ssh:\/\/git@github\.com\/([^/\s]+\/[^/\s]+?)(?:\.git)?\/?$/i,
];
export const githubId = url => { const text = String(url).trim(); for (const pattern of GITHUB_URLS) { const match = pattern.exec(text); if (match) return match[1]; } return null; };

// Git clones directly under root whose origin is a GitHub repository other than the template.
// Two folders on the same repository collapse to one, preferring the folder named after it.
export async function findClones({ root, execute = run, template = TEMPLATE }) {
  const found = new Map();
  for (const entry of await readdir(root, { withFileTypes: true }).catch(() => [])) {
    if (!entry.isDirectory()) continue;
    const folder = path.join(root, entry.name);
    if (!await lstat(path.join(folder, '.git')).catch(() => null)) continue;
    const id = githubId(await execute('git', ['-C', folder, 'config', '--get', 'remote.origin.url']).catch(() => ''));
    if (!id || id.toLowerCase() === template.toLowerCase()) continue;
    try { validateRepo(id); } catch { continue; }
    const previous = found.get(id.toLowerCase());
    if (!previous || (entry.name.toLowerCase() === id.split('/')[1].toLowerCase() && previous.name.toLowerCase() !== previous.id.split('/')[1].toLowerCase())) found.set(id.toLowerCase(), { id, name: entry.name, folder });
  }
  return [...found.values()].sort((a, b) => a.id.localeCompare(b.id));
}

// A template without this part of the skill counts as empty, so every local file shows as added.
async function fileDiff(template, git, rev, name, part = PARTS[0]) {
  const list = async (run, tree) => new Map(parseTree(await run(['ls-tree', '-z', '-r', tree])).map(entry => [entry.path, entry.sha]));
  const theirs = template.current[part].has(name) ? await list(template.git, `${template.head}:${part}/${name}`) : new Map();
  const ours = await list(git, `${rev}:${part}/${name}`);
  return {
    changed: [...ours.keys()].filter(file => theirs.has(file) && theirs.get(file) !== ours.get(file)),
    added: [...ours.keys()].filter(file => !theirs.has(file)),
    missing: [...theirs.keys()].filter(file => !ours.has(file)),
  };
}

// Status of every template skill (and every former template skill) in one repository at rev.
// A native Codex copy under .agents/skills is hand-maintained, so it counts as part of the skill.
// Generated adapters are rebuilt by the repository's own generator instead. The repository's own
// Codex mode for a skill wins over the template's; one without skill-modes.json has no native mode,
// and a skill turned off in settings gets no Codex copy.
export async function compareRepo({ template, folder, rev = 'origin/main', execute = run }) {
  const git = args => execute('git', ['-C', folder, ...args]);
  const local = await skillTrees(git, rev);
  const overrides = (await showJson(git, rev, '.claude/settings.json'))?.skillOverrides ?? {};
  const modes = (await showJson(git, rev, '.agents/skill-modes.json'))?.skills;
  const nativeCopies = new Set([...template.current[PARTS[0]].keys()].filter(name => modes && overrides[name] !== 'off' && (modes[name] ?? template.modes[name]) === 'native'));
  const units = name => nativeCopies.has(name) ? PARTS : [PARTS[0]];
  const pristine = (part, name) => local.odd.has(`${part}/${name}`) ? false : !local[part].has(name) ? part !== PARTS[0] : Boolean(template.history[part].get(name)?.has(local[part].get(name)));
  // Whatever the mode, a Codex copy that is neither a past template tree nor a generated adapter
  // was written by hand in this repository, and adding or removing the skill would destroy it.
  // The generator writes SKILL.md alone, so any other file in the folder was added by hand.
  const generated = async name => {
    const entries = parseTree(await git(['ls-tree', '-z', `${rev}:${PARTS[1]}/${name}`]).catch(() => ''));
    if (entries.length !== 1 || entries[0].path !== 'SKILL.md' || entries[0].type !== 'blob' || entries[0].mode === '120000') return false;
    return git(['cat-file', 'blob', entries[0].sha]).then(text => text.includes(ADAPTER_MARKER), () => false);
  };
  const codexSafe = async name => pristine(PARTS[1], name) || await generated(name);
  // An edited skill carries its folder trees, so replacing it can refuse a copy edited again since
  // the check, and whether its Codex copy was written by hand (replacing it drops that copy too).
  const fingerprint = name => PARTS.map(part => local.odd.has(`${part}/${name}`) ? 'file' : local[part].get(name) ?? '-').join(':');
  const edited = async (name, files) => ({ name, status: 'customized', files, trees: fingerprint(name), handCodex: (local[PARTS[1]].has(name) || local.odd.has(`${PARTS[1]}/${name}`)) && !await generated(name) });
  const skills = [];
  for (const name of template.current[PARTS[0]].keys()) {
    // Off wins even over an existing folder: the repository chose not to track this skill.
    if (overrides[name] === 'off') { skills.push({ name, status: 'off' }); continue; }
    if (!local[PARTS[0]].has(name)) {
      if (!local.odd.has(`${PARTS[0]}/${name}`) && await codexSafe(name)) skills.push({ name, status: 'new' });
      // A file where a folder belongs has no per-file diff; the UI then says the copy differs.
      else skills.push(await edited(name, local.odd.has(`${PARTS[1]}/${name}`) || local.odd.has(`${PARTS[0]}/${name}`) ? { changed: [], added: [], missing: [] } : await fileDiff(template, git, rev, name, PARTS[1])));
      continue;
    }
    if (units(name).every(part => local[part].get(name) === template.current[part].get(name))) { skills.push({ name, status: 'same' }); continue; }
    if (units(name).every(part => pristine(part, name))) { skills.push({ name, status: 'behind' }); continue; }
    skills.push(await edited(name, await fileDiff(template, git, rev, name)));
  }
  for (const name of local[PARTS[0]].keys()) {
    if (template.current[PARTS[0]].has(name) || !template.history[PARTS[0]].has(name)) continue;
    skills.push({ name, status: pristine(PARTS[0], name) && await codexSafe(name) ? 'removed' : 'removed-edited' });
  }
  // A Codex-only skill is its .agents folder alone. A repository without skill-modes.json has no Codex
  // setup to receive one, and a repository with its own Claude copy of the name owns that skill.
  for (const name of template.codexOnly) {
    if (!modes || local[PARTS[0]].has(name) || local.odd.has(`${PARTS[0]}/${name}`)) continue;
    if (overrides[name] === 'off' || modes[name] === 'disabled') skills.push({ name, codex: true, status: 'off' });
    else if (local.odd.has(`${PARTS[1]}/${name}`)) skills.push({ ...await edited(name, { changed: [], added: [], missing: [] }), codex: true });
    else if (!local[PARTS[1]].has(name)) skills.push({ name, codex: true, status: 'new' });
    else if (local[PARTS[1]].get(name) === template.current[PARTS[1]].get(name)) skills.push({ name, codex: true, status: 'same' });
    // A generated adapter with no Claude copy behind it is a leftover the template copy can replace.
    else if (pristine(PARTS[1], name) || await generated(name)) skills.push({ name, codex: true, status: 'behind' });
    else skills.push({ ...await edited(name, await fileDiff(template, git, rev, name, PARTS[1])), codex: true });
  }
  // A retired Codex-only skill: the template had only its .agents folder, never a Claude copy, and no
  // longer has its SKILL.md (a leftover file can keep the folder). Same Codex setup rule as additions.
  for (const name of local[PARTS[1]].keys()) {
    if (!modes || local[PARTS[0]].has(name) || local.odd.has(`${PARTS[0]}/${name}`) || template.current[PARTS[0]].has(name) || template.codexOnly.has(name) || template.history[PARTS[0]].has(name) || !template.history[PARTS[1]].has(name)) continue;
    skills.push({ name, codex: true, status: pristine(PARTS[1], name) || await generated(name) ? 'removed' : 'removed-edited' });
  }
  const harness = [...local[PARTS[0]].keys()].some(name => template.history[PARTS[0]].has(name));
  // A locked skill keeps its own status in `was` and offers nothing to pick, whatever it would have been.
  const locks = await readLocks(git, rev);
  // Its other fields stay, so the compare view still shows a hand-written Codex copy or a retired skill.
  const shown = skills.map(skill => locks.has(skill.name) ? { ...skill, status: 'locked', reason: locks.get(skill.name), was: skill.status } : skill);
  return { harness, nativeCopies, skills: shown.sort((a, b) => a.name.localeCompare(b.name)) };
}

// Checkouts of a clone (its own folder and every linked worktree) whose committed skill copies are
// an older template version than the repository's main. A session loads skills from its own
// checkout, so a branch cut before a skill sync keeps running old copies while main looks current.
// Copies edited in the branch are not past template trees and are left out, and so are skills the
// checkout turns off. When main holds an edited copy, any past template copy counts as older. Read-only.
export async function staleWorktrees({ template, folder, rev = 'origin/main', execute = run }) {
  const git = args => execute('git', ['-C', folder, ...args]);
  const main = await skillTrees(git, rev);
  const entries = (await git(['worktree', 'list', '--porcelain']).catch(() => '')).split(/\r?\n\r?\n/).map(block => Object.fromEntries(block.split(/\r?\n/).filter(Boolean).map(line => {
    const at = line.indexOf(' '); return at < 0 ? [line, true] : [line.slice(0, at), line.slice(at + 1)];
  })));
  // Git prints each checkout's real path, so a root reached through a junction or an 8.3 short name
  // has to be resolved the same way before the clone's own checkout can be recognized.
  const long = async where => (await realpath(where).catch(() => path.resolve(where))).toLowerCase();
  const self = await long(folder);
  const found = [];
  for (const entry of entries) {
    if (!entry.worktree || !entry.HEAD || entry.bare || entry.prunable || !await exists(entry.worktree)) continue;
    const trees = await skillTrees(git, entry.HEAD);
    const overrides = (await showJson(git, entry.HEAD, '.claude/settings.json'))?.skillOverrides ?? {};
    const skills = new Set();
    for (const part of PARTS) for (const [name, sha] of trees[part]) {
      const theirs = main[part].get(name), ages = template.age[part].get(name);
      if (overrides[name] === 'off' || !theirs || sha === theirs || sha === template.current[part].get(name) || !ages?.has(sha)) continue;
      if (!ages.has(theirs) || ages.get(theirs) < ages.get(sha)) skills.add(name);
    }
    if (!skills.size) continue;
    const where = path.resolve(entry.worktree);
    found.push({ path: where, own: await long(where) === self, branch: entry.branch ? entry.branch.replace(/^refs\/heads\//, '') : null, head: entry.HEAD.slice(0, 7), skills: [...skills].sort() });
  }
  return found;
}

async function limit(items, size, work) {
  const results = new Array(items.length); let next = 0;
  await Promise.all(Array.from({ length: Math.min(size, items.length) }, async () => { while (next < items.length) { const index = next++; results[index] = await work(items[index]); } }));
  return results;
}

// Fetches each clone's origin/main (the working folder itself is never touched) and compares it.
// A skip-listed clone is not fetched. Every other clone is looked up on GitHub before the fetch, so
// one whose origin uses a name from before a rename matches a skip entry under the current name and
// is not fetched either. Whether a clone is a Harness clone needs the fetched tree, so an archived
// repository or a failed lookup is reported only for a Harness clone; other clones stay unlisted.
// Skipped and failed repositories carry no skills, so none can be picked.
export async function scanSkills({ root, execute = run, template: opened, cache, source, skip } = {}) {
  const skipList = skip ?? await readSkipList();
  const template = opened ?? await openTemplate({ cache, source, execute });
  const clones = await findClones({ root, execute });
  const repos = await limit(clones, 6, async clone => {
    const listed = skipReason(skipList, clone.id);
    if (listed !== null) return { ...clone, harness: true, skipped: listed };
    const github = await githubState(clone.id, execute);
    const renamed = github.name ? skipReason(skipList, github.name) : null;
    if (renamed !== null) return { ...clone, harness: true, skipped: renamed };
    let repo, head;
    try {
      await execute('git', ['-C', clone.folder, ...GIT_CRED, 'fetch', '--quiet', 'origin', 'main']);
      head = (await execute('git', ['-C', clone.folder, 'rev-parse', 'origin/main'])).trim();
    } catch (error) { return { ...clone, harness: true, error: `Could not fetch. ${reason(error)}` }; }
    try {
      const worktrees = await staleWorktrees({ template, folder: clone.folder, execute }).catch(() => []);
      repo = { ...clone, head, ...await compareRepo({ template, folder: clone.folder, execute }), worktrees };
    } catch (error) { return { ...clone, harness: true, error: `Could not compare. ${reason(error)}` }; }
    if (!repo.harness) return repo;
    return github.skipped ? { ...clone, harness: true, skipped: github.skipped } : github.blocked ? { ...clone, harness: true, error: github.blocked } : repo;
  });
  return { template: { id: TEMPLATE, head: template.head }, repos: repos.filter(repo => repo.harness).map(({ harness, nativeCopies, ...repo }) => repo) };
}

// Template files under the given skill folders at head, contents fetched in one round trip.
async function templateFiles(template, folders, execute) {
  if (!folders.length) return [];
  const entries = parseTree(await template.git(['ls-tree', '-z', '-r', template.head, '--', ...folders.map(folder => `${folder}/`)]));
  const odd = entries.find(entry => entry.type !== 'blob' || entry.mode === '120000');
  if (odd) throw new Error(`${odd.path} is not a regular file; sync it by hand.`);
  await templateBlobs(template, entries, execute);
  return entries;
}
// The cache is blobless: fetch missing files in batches instead of one lazy fetch per file.
// A failed batch fetch is not fatal; cat-file still fetches lazily what is absent.
async function templateBlobs(template, entries, execute) {
  const missing = [...new Set(entries.filter(entry => !template.blobs.has(entry.sha)).map(entry => entry.sha))];
  for (let index = 0; index < missing.length; index += 200) await execute('git', ['--git-dir', template.cache, ...GIT_CRED, 'fetch', '--quiet', '--no-write-fetch-head', 'origin', ...missing.slice(index, index + 200)]).catch(() => {});
  if (missing.length) for (const [sha, data] of await readBlobs(template.cache, missing)) template.blobs.set(sha, data);
}

// Unified diff from a repository's copy of one skill at rev to the template copy a sync would write.
// Each side holds the folders a sync touches: the Claude copy, plus the .agents copy where it is
// native, Codex-only, or hand-written here. A generated adapter is left out; the generator rebuilds it.
// A removal deletes every folder of the skill, so its template side is empty.
export async function compareSkill({ folder, rev, name, templateHead, template = latestTemplate, execute = run }) {
  if (!SKILL_NAME.test(name)) throw new Error('Invalid skill name.');
  if (!template || template.head !== templateHead) throw new Error('Check repositories again.');
  const git = args => execute('git', ['-C', folder, ...args]);
  const { skills, nativeCopies } = await compareRepo({ template, folder, rev, execute });
  const skill = skills.find(item => item.name === name);
  if (!skill) throw new Error(`${name} is not a Harness skill in this repository.`);
  const codex = skill.codex || template.codexOnly.has(name), removal = ['removed', 'removed-edited'].includes(skill.was ?? skill.status);
  const ours = PARTS.filter(part => part === PARTS[0] ? !codex : codex || removal || nativeCopies.has(name) || skill.handCodex);
  const theirs = removal ? [] : PARTS.filter(part => template.current[part].has(name) && (part === PARTS[0] ? !codex : codex || nativeCopies.has(name)));
  // No trailing slash: a file or symlink where the skill folder belongs is listed too, since a
  // replacement deletes it. Symlinks are written as their target text; submodules have no bytes.
  const files = async (read, tree, parts) => parts.length ? parseTree(await read(['ls-tree', '-z', '-r', tree, '--', ...parts.map(part => `${part}/${name}`)])).filter(entry => entry.type === 'blob') : [];
  const mine = await files(git, rev, ours), incoming = await files(template.git, template.head, theirs);
  // Scratch files carry no Git mode, so a sync's executable-bit change is listed ahead of the diff.
  const modes = new Map(mine.map(entry => [entry.path, entry.mode]));
  const modeLines = incoming.filter(entry => modes.has(entry.path) && modes.get(entry.path) !== entry.mode).map(entry => `mode ${modes.get(entry.path)} -> ${entry.mode}: ${entry.path}\n`).join('');
  await templateBlobs(template, incoming, execute);
  const local = mine.length ? await readBlobs((await git(['rev-parse', '--absolute-git-dir'])).trim(), [...new Set(mine.map(entry => entry.sha))]) : new Map();
  const scratch = await mkdtemp(path.join(tmpdir(), 'corewise-sync-compare-'));
  try {
    // Short side names, so the diff headers read repo/... and harness-firmware/....
    const write = async (side, entries, blobs) => {
      await mkdir(path.join(scratch, side), { recursive: true });
      for (const entry of entries) {
        const target = path.join(scratch, side, ...entry.path.split('/'));
        await mkdir(path.dirname(target), { recursive: true }); await writeFile(target, blobs.get(entry.sha));
      }
    };
    await write('repo', mine, local); await write('harness-firmware', incoming, template.blobs);
    return await new Promise((resolve, reject) => {
      const child = spawn('git', ['-c', 'core.quotePath=false', 'diff', '--no-index', '--no-color', '--', 'repo', 'harness-firmware'], { cwd: scratch, windowsHide: true, shell: false, stdio: ['ignore', 'pipe', 'pipe'] });
      let out = '', err = ''; child.stdout.on('data', data => { out += data; }); child.stderr.on('data', data => { err += data; });
      child.on('error', reject);
      child.on('close', code => code <= 1 ? resolve((`${modeLines}${out}` || 'No differences.\n').slice(0, 200_000)) : reject(new Error(err.trim() || `git diff exited with code ${code}`)));
    });
  } finally { await rm(scratch, { recursive: true, force: true }); }
}

// Tree hash of each "<commit>:<path>" spec through one `git cat-file --batch-check`; null where absent.
function treesAt(gitArgs, specs) {
  if (!specs.length) return Promise.resolve([]);
  return new Promise((resolve, reject) => {
    const child = spawn('git', [...gitArgs, 'cat-file', '--batch-check'], { windowsHide: true, shell: false, stdio: ['pipe', 'pipe', 'pipe'] });
    let out = '', err = ''; child.stdout.on('data', data => { out += data; }); child.stderr.on('data', data => { err += data; });
    child.on('error', reject);
    child.on('close', code => code === 0 ? resolve(out.split(/\r?\n/).filter(Boolean).map(line => { const [sha, type] = line.split(' '); return type === 'tree' ? sha : null; })) : reject(new Error(err.trim() || `git cat-file exited with code ${code}`)));
    child.stdin.end(specs.map(spec => `${spec}\n`).join(''));
  });
}
const commitsOf = async (read, rev, targets) => (await read(['log', '--format=%H%x1f%cI%x1f%an%x1f%s', rev, '--', ...targets])).split(/\r?\n/).filter(Boolean)
  .map(line => { const [sha, date, author, subject] = line.split('\x1f'); return { sha, date, author, subject }; });
const STORY_SHOWN = 20;

// Where one skill copy came from, for the compare view: the newest repository commit whose copy
// matches a template version (the last time both sides agreed), the commits on each side since,
// and that shared copy's text, so each changed line can be credited to the side that changed it.
// History covers the Codex copy too where a sync maintains it (native or hand-written), so an edit to
// that copy alone still counts; a generated adapter is rebuilt by the repository and is left out.
export async function skillStory({ folder, rev, name, templateHead, template = latestTemplate, execute = run }) {
  if (!SKILL_NAME.test(name)) throw new Error('Invalid skill name.');
  if (!template || template.head !== templateHead) throw new Error('Check repositories again.');
  const targets = PARTS.map(part => `${part}/${name}`), key = template.history[PARTS[0]].has(name) ? 0 : 1, other = 1 - key;
  const { skills, nativeCopies } = await compareRepo({ template, folder, rev, execute });
  const maintained = key === 0 && (nativeCopies.has(name) || Boolean(skills.find(item => item.name === name)?.handCodex));
  const paths = maintained ? targets : [targets[key]];
  const git = args => execute('git', ['-C', folder, ...args]);
  const [ours, theirs] = await Promise.all([commitsOf(git, rev, paths), commitsOf(template.git, template.head, paths)]);
  // Trees per commit, one list per folder: [claudeTrees, codexTrees].
  const trees = (gitArgs, commits) => Promise.all(targets.map(target => treesAt(gitArgs, commits.map(item => `${item.sha}:${target}`))));
  const [ourTrees, theirTrees] = await Promise.all([trees(['-C', folder], ours), trees(['--git-dir', template.cache], theirs)]);
  // A match: the main folder is a template copy, and a maintained Codex copy is absent or one too.
  const known = template.history[PARTS[key]].get(name) ?? new Set(), otherKnown = template.history[PARTS[other]].get(name) ?? new Set();
  let at = ourTrees[key].findIndex((tree, index) => tree && known.has(tree) && (!maintained || !ourTrees[other][index] || otherKnown.has(ourTrees[other][index])));
  if (at < 0) at = ourTrees[key].findIndex(tree => tree && known.has(tree));
  // The template commit that copy came from: the newest with the same folders.
  const same = (index, part) => theirTrees[part][index] === ourTrees[part][at];
  let from = -1;
  if (at >= 0) { from = theirs.findIndex((_, index) => same(index, key) && (!maintained || same(index, other))); if (from < 0) from = theirs.findIndex((_, index) => same(index, key)); }
  const baseFiles = {};
  if (from >= 0) {
    const entries = parseTree(await template.git(['ls-tree', '-z', '-r', theirs[from].sha, '--', ...paths.map(target => `${target}/`)])).filter(entry => entry.type === 'blob' && entry.mode !== '120000');
    await templateBlobs(template, entries, execute);
    for (const entry of entries) baseFiles[entry.path] = template.blobs.get(entry.sha)?.toString('utf8') ?? '';
  }
  const side = (commits, index) => { const since = index < 0 ? commits : commits.slice(0, index); return { last: commits[0] ?? null, since: since.slice(0, STORY_SHOWN), count: since.length }; };
  return {
    template: TEMPLATE,
    repo: side(ours, at), harness: side(theirs, from),
    base: at >= 0 ? { repo: ours[at], harness: theirs[from] ?? null } : null,
    baseFiles,
  };
}

// Replaces whole skill folders: dropped folders go, template folders arrive byte for byte.
async function writeFolders(template, worktree, git, replace, drop, execute) {
  const entries = await templateFiles(template, replace, execute);
  // git add fails on a pathspec that matches nothing, so only folders that exist before or after count.
  const staged = [...replace];
  for (const folder of [...replace, ...drop]) {
    const full = path.join(worktree, ...folder.split('/'));
    if (drop.includes(folder) && await exists(full)) staged.push(folder);
    await rm(full, { recursive: true, force: true });
  }
  for (const entry of entries) {
    const target = path.join(worktree, ...entry.path.split('/'));
    await mkdir(path.dirname(target), { recursive: true });
    await writeFile(target, template.blobs.get(entry.sha));
  }
  if (staged.length) await git(['add', '-A', '--', ...staged]);
  const executable = entries.filter(entry => entry.mode === '100755').map(entry => entry.path);
  if (executable.length) await git(['update-index', '--chmod=+x', '--', ...executable]);
}

// Copies or drops a skill's registry entries so the repository's Codex checks stay consistent.
// A Codex mode the repository already chose is kept; the template fills in a missing one. A source
// hash follows the folders: a skill that receives the template's native Codex copy gets the template's
// hash, since its Claude folder is now the template's byte for byte. Registry files the repository
// does not have are not created.
async function writeRegistries(template, worktree, updates, nativeCopies) {
  for (const file of REGISTRIES) {
    const full = path.join(worktree, ...file.split('/'));
    if (!await exists(full)) continue;
    const text = await readFile(full, 'utf8'); const data = JSON.parse(text);
    if (!data.skills || typeof data.skills !== 'object') continue;
    for (const [name, keep] of updates) {
      const entry = template.registries[file]?.skills?.[name];
      if (!keep) delete data.skills[name];
      else if (file === SOURCES) { if (nativeCopies.has(name) && typeof entry === 'string') data.skills[name] = entry; }
      else if (entry !== undefined && data.skills[name] === undefined) data.skills[name] = entry;
    }
    if (JSON.stringify(JSON.parse(text)) === JSON.stringify(data)) continue;
    // The template's own --baseline writes sources sorted by name; keep that order so it adds no churn.
    if (file === SOURCES) data.skills = Object.fromEntries(Object.entries(data.skills).sort(([a], [b]) => a < b ? -1 : a > b ? 1 : 0));
    await writeFile(full, `${JSON.stringify(data, null, 2)}\n`);
  }
}

// Keeps the compatibility table in step with the skills: an added skill the table does not list goes
// into the row the template gives it, a removed skill leaves its row. Only rows that are a plain list
// of skills, or hold no skill at all, are rewritten; a row with other text is left for the checks to
// report. A status the table has no row for gets one after the last status row. A repository without
// the table gets none.
async function writeCompatibility(template, worktree, add, drop) {
  const full = path.join(worktree, ...COMPATIBILITY.split('/'));
  if (!await exists(full)) return;
  const text = await readFile(full, 'utf8'); const eol = text.includes('\r\n') ? '\r\n' : '\n';
  const listed = classifications(text);
  const moves = new Map(drop.filter(name => listed.has(name)).map(name => [name, null]));
  for (const name of add) if (!listed.has(name) && template.classes.has(name)) moves.set(name, template.classes.get(name));
  if (!moves.size) return;
  const sorted = names => names.sort((a, b) => a < b ? -1 : a > b ? 1 : 0);
  const row = (status, names) => `| ${status} | ${names.length ? sorted(names).map(name => `\`${name}\``).join(', ') : 'None.'} |`;
  const rows = new Set(); let last = -1;
  const lines = text.split(/\r?\n/).map((line, index) => {
    const match = CLASS_ROW.exec(line); if (!match) return line;
    rows.add(match[1]); last = index;
    const cell = match[2].trim(), skills = [...cell.matchAll(/`([^`]+)`/g)].map(skill => skill[1]);
    if (skills.length && !/^`[^`]+`(?:\s*,\s*`[^`]+`)*$/.test(cell)) return line;
    const kept = skills.filter(name => !moves.has(name)).concat([...moves].filter(([, status]) => status === match[1]).map(([name]) => name));
    if (kept.length === skills.length && kept.every((name, index) => name === skills[index])) return line;
    return row(match[1], kept);
  });
  if (last < 0) return;
  const missing = new Map();
  for (const [name, status] of moves) if (status && !rows.has(status)) missing.set(status, [...missing.get(status) ?? [], name]);
  lines.splice(last + 1, 0, ...[...missing].map(([status, names]) => row(status, names)));
  await writeFile(full, lines.join(eol));
}

// Runs one of the repository's own Node scripts in the worktree: { ok, out } or { ok: false, error }.
const node = (script, args, cwd, execute) => execute(process.execPath, [script, ...args], { cwd }).then(out => ({ ok: true, out }), error => ({ ok: false, error }));

// One branch per template version. A branch left by an earlier sync of the same version is never
// overwritten; the new one gets a numbered suffix instead.
async function freeBranch(git, base) {
  const taken = new Set((await git([...GIT_CRED, 'ls-remote', '--heads', 'origin'])).split(/\r?\n/).map(line => line.split('\t')[1]).filter(Boolean));
  for (let index = 1; ; index++) { const name = index === 1 ? base : `${base}-${index}`; if (!taken.has(`refs/heads/${name}`)) return name; }
}

// removed-skills.mjs only warns; the pull request lists what it printed.
function removedSummary(result) {
  if (!result.ok) return [`- removed-skills.mjs: could not run (${reason(result.error)}); it only warns, so this does not block`];
  const warnings = result.out.split(/\r?\n/).map(line => /^(?:WARN: |::warning::)(.+)$/.exec(line.trim())?.[1]).filter(Boolean);
  if (!warnings.length) return ['- removed-skills.mjs: no warnings'];
  const shown = warnings.slice(0, 10).map(line => `  - ${line}`);
  return [`- removed-skills.mjs: ${warnings.length} ${warnings.length === 1 ? 'warning' : 'warnings'}, not blocking:`, ...shown, ...(warnings.length > shown.length ? [`  - and ${warnings.length - shown.length} more`] : [])];
}

// Pushes the worktree's commit to a new branch, opens a pull request into main and squash-merges it.
// Main is never pushed to directly. Returns { branch, url }; a failure after the push carries them.
async function mergeCommit({ git, execute, worktree, github, commit, base, title, body, say }) {
  const branch = await freeBranch(git, base);
  // A plain push of a new branch: it never moves main and never overwrites an existing branch.
  await git([...GIT_CRED, 'push', '--quiet', 'origin', `HEAD:refs/heads/${branch}`]);
  // Run from the worktree, whose origin is this repository, in case gh reads the local remotes.
  let out;
  try { out = await execute('gh', ['pr', 'create', '--repo', github.name, '--base', github.branch, '--head', branch, '--title', title, '--body', body], { cwd: worktree }); }
  catch (error) { throw Object.assign(new Error(`Pushed branch ${branch}, but could not open the pull request: ${reason(error)}. Open it on GitHub by hand.`), { branch }); }
  const url = String(out).split(/\r?\n/).map(line => line.trim()).find(line => /^https:\/\/github\.com\/[^\s/]+\/[^\s/]+\/pull\/\d+$/.test(line)) ?? null;
  if (!url) throw Object.assign(new Error(`Opened a pull request from ${branch}, but gh printed no link to merge. Merge it on GitHub by hand.`), { branch });
  // Squash-merged straight away, pinned to the commit the checks ran on. A merge GitHub refuses
  // (branch protection, required checks, a conflict with a newer main, a branch that moved since
  // the push) leaves the pull request open and fails this repository.
  try { await execute('gh', ['pr', 'merge', url, '--squash', '--match-head-commit', commit], { cwd: worktree }); }
  catch (error) { throw Object.assign(new Error(`Opened ${url}, but could not merge it: ${reason(error)}. Merge it on GitHub by hand.`), { branch, url }); }
  // On a branch with a merge queue, gh pr merge can succeed by queueing the pull request or turning on
  // auto-merge. The branch is deleted only once GitHub reports the pull request merged; a state that
  // cannot be read after three tries is reported as unconfirmed, and the branch stays.
  let state = '', lookup = null;
  for (let attempt = 0; attempt < 3 && !state; attempt++) {
    if (attempt) await new Promise(resolve => setTimeout(resolve, 1000));
    try { state = String(await execute('gh', ['pr', 'view', url, '--json', 'state', '--jq', '.state'], { cwd: worktree })).trim(); lookup = null; }
    catch (error) { lookup = error; }
  }
  if (!state) throw Object.assign(new Error(`Asked GitHub to merge ${url}, but could not confirm the merge: ${reason(lookup)}. Check it on GitHub; the branch stays.`), { branch, url });
  if (state !== 'MERGED') throw Object.assign(new Error(`Opened ${url}; GitHub queued it instead of merging (state ${state}). It merges when its checks pass; the branch stays until then.`), { branch, url });
  await git([...GIT_CRED, 'push', '--quiet', 'origin', '--delete', branch]).catch(() => say(`merged, but could not delete branch ${branch}`));
  return { branch, url };
}

// Applies one repository's selection in a temporary worktree on origin/main, pushes it to a new
// branch, opens a pull request into main and squash-merges it. Main is never pushed to directly.
async function applyRepo({ template, clone, skipList, apply, remove, replace, execute, onOutput }) {
  const say = text => onOutput(`${clone.id}: ${text}\n`);
  const github = await githubState(clone.id, execute);
  // The skip list also matches the name GitHub reports, which follows a rename the origin may still use.
  const listed = github.name ? skipReason(skipList, github.name) : null;
  if (listed !== null) throw new Error(`Skipped: ${listed}. Nothing was written.`);
  if (github.skipped) throw new Error(`Skipped: ${github.skipped}. Nothing was written.`);
  if (github.blocked) throw new Error(github.blocked);
  await execute('git', ['-C', clone.folder, ...GIT_CRED, 'fetch', '--quiet', 'origin', 'main']);
  const head = (await execute('git', ['-C', clone.folder, 'rev-parse', 'origin/main'])).trim();
  const { skills, nativeCopies } = await compareRepo({ template, folder: clone.folder, rev: head, execute });
  const status = new Map(skills.map(skill => [skill.name, skill.status])), found = new Map(skills.map(skill => [skill.name, skill]));
  const take = apply.filter(name => ['behind', 'new'].includes(status.get(name)));
  const drop = remove.filter(name => status.get(name) === 'removed');
  // An edited copy is replaced only while it is still the copy the check saw.
  const swap = replace.filter(({ name, trees }) => status.get(name) === 'customized' && found.get(name).trees === trees).map(({ name }) => name);
  for (const name of [...apply, ...remove].filter(name => !take.includes(name) && !drop.includes(name))) say(`skipped ${name}, now ${status.get(name) ?? 'absent'} on GitHub`);
  for (const { name } of replace.filter(({ name }) => !swap.includes(name))) say(`skipped ${name}, ${status.get(name) === 'customized' ? 'edited again on GitHub since the check' : `now ${status.get(name) ?? 'absent'} on GitHub`}`);
  if (!take.length && !drop.length && !swap.length) { say('nothing to apply'); return { id: clone.id, result: 'current' }; }

  // The long form, so it matches the path `git worktree list` prints when checking cleanup.
  const temp = await realpath(await mkdtemp(path.join(tmpdir(), 'corewise-sync-')));
  const worktree = path.join(temp, 'work');
  const git = args => execute('git', ['-C', worktree, ...args]);
  try {
    await execute('git', ['-C', clone.folder, 'worktree', 'add', '--quiet', '--detach', worktree, head]);
    const script = name => path.join(worktree, '.claude', 'scripts', name);
    const has = Object.fromEntries(await Promise.all(['sync-codex-skills.mjs', 'test-codex-contract.mjs', 'removed-skills.mjs'].map(async name => [name, await exists(script(name))])));
    const before = {
      codex: has['sync-codex-skills.mjs'] && await node(script('sync-codex-skills.mjs'), ['--check'], worktree, execute),
      contract: has['test-codex-contract.mjs'] && await node(script('test-codex-contract.mjs'), [], worktree, execute),
    };

    // Only skills whose Codex copy is native here, and Codex-only skills, receive the template's .agents folder.
    // A replaced skill loses a hand-written Codex copy the template does not supply, so the repository's
    // generator can write its adapter; a generated adapter stays for the generator to rebuild.
    const incoming = name => PARTS.filter(part => template.current[part].has(name) && (part === PARTS[0] || nativeCopies.has(name) || template.codexOnly.has(name)));
    const folders = [...take, ...swap].flatMap(name => incoming(name).map(part => `${part}/${name}`));
    const handDrops = swap.filter(name => found.get(name).handCodex && !incoming(name).includes(PARTS[1])).map(name => `${PARTS[1]}/${name}`);
    await writeFolders(template, worktree, git, folders, [...drop.flatMap(name => PARTS.map(part => `${part}/${name}`)), ...handDrops], execute);
    await writeRegistries(template, worktree, [...take, ...swap].map(name => [name, true]).concat(drop.map(name => [name, false])), nativeCopies);
    await writeCompatibility(template, worktree, [...take, ...swap], drop);

    // A check that passed on main must still pass after the change, or nothing is committed or pushed.
    // One already failing on main is reported in the pull request; its own CI shows the rest.
    const checks = [];
    const judge = (label, was, now) => {
      if (now.ok) { checks.push(`- ${label}: ${was.ok ? 'passed on main and after this change' : 'failed on main, passes after this change'}`); return; }
      if (was.ok) throw new Error(`${label} fails after the change: ${reason(now.error)}`);
      checks.push(`- ${label}: already failing on main (${reason(was.error)}); still fails after this change (${reason(now.error)})`);
      say(`${label} was already failing on main; opening the pull request anyway`);
    };
    if (has['sync-codex-skills.mjs']) {
      // The repository's own generator rebuilds its Codex adapters before the check.
      const wrote = await node(script('sync-codex-skills.mjs'), ['--write'], worktree, execute);
      // The generator runs over every skill, so a locked skill's folders go back to main's copy before the check.
      const kept = skills.filter(skill => skill.status === 'locked').flatMap(skill => PARTS.map(part => `${part}/${skill.name}`));
      if (kept.length) {
        const tracked = (await git(['ls-tree', '--name-only', 'HEAD', '--', ...kept])).split(/\r?\n/).filter(Boolean);
        if (tracked.length) await git(['checkout', 'HEAD', '--', ...tracked]);
        await git(['clean', '-fdq', '--', ...kept]);
      }
      judge('sync-codex-skills.mjs --check', before.codex, wrote.ok ? await node(script('sync-codex-skills.mjs'), ['--check'], worktree, execute) : wrote);
    } else checks.push('- sync-codex-skills.mjs: not in this repository, not run');
    if (has['test-codex-contract.mjs']) judge('test-codex-contract.mjs', before.contract, await node(script('test-codex-contract.mjs'), [], worktree, execute));
    else checks.push('- test-codex-contract.mjs: not in this repository, not run');
    if (has['removed-skills.mjs']) checks.push(...removedSummary(await node(script('removed-skills.mjs'), [], worktree, execute)));
    else checks.push('- removed-skills.mjs: not in this repository, not run');

    await git(['add', '-A']);
    if (await git(['diff', '--cached', '--quiet']).then(() => true, () => false)) { say('already current'); return { id: clone.id, result: 'current' }; }
    const updated = take.filter(name => status.get(name) === 'behind'), added = take.filter(name => status.get(name) === 'new');
    const changes = [updated.length && `Updated: ${updated.join(', ')}`, added.length && `Added: ${added.join(', ')}`, swap.length && `Replaced edited copies: ${swap.join(', ')}`, drop.length && `Removed: ${drop.join(', ')}`].filter(Boolean);
    const source = `Template: ${TEMPLATE}@${template.head.slice(0, 7)}`;
    await git(['commit', '-q', '-m', PR_TITLE, '-m', [...changes, source].join('\n')]);
    const commit = (await git(['rev-parse', 'HEAD'])).trim();
    const body = [...changes, source, '', 'Checks run on this change in a temporary checkout of main before it was committed:', ...checks, '', 'Opened by Harness Console skill sync.'].join('\n');
    const { branch, url } = await mergeCommit({ git, execute, worktree, github, commit, base: `harness-sync/${template.head.slice(0, 7)}`, title: PR_TITLE, body, say });
    say(`merged ${url} (${changes.join('; ')})`);
    return { id: clone.id, result: 'merged', commit, branch, url };
  } finally {
    await removeWorktree(clone.folder, temp, worktree, execute, say);
  }
}

// An editor or virus scanner holding a file open can block removal for a moment, so retry once;
// whatever still remains is named so it can be removed by hand instead of piling up unseen.
// Never a blanket `git worktree prune`: that would also drop the user's own stale registrations
// (a worktree on an unplugged drive). Only this worktree's admin entry goes, and only unlocked,
// the same rule prune follows.
async function removeWorktree(folder, temp, worktree, execute, say) {
  const same = (a, b) => path.resolve(a).toLowerCase() === path.resolve(b).toLowerCase();
  // The worktree's .git file names its admin entry (<common dir>/worktrees/<id>); read it before removal.
  const pointer = await readFile(path.join(worktree, '.git'), 'utf8').then(text => /^gitdir:\s*(.+)$/m.exec(text)?.[1].trim(), () => null);
  const admin = pointer && path.resolve(worktree, pointer);
  const dropAdmin = async () => {
    if (!admin || await exists(path.join(admin, 'locked'))) return;
    const back = await readFile(path.join(admin, 'gitdir'), 'utf8').then(text => text.trim(), () => null);
    if (back && same(path.dirname(path.resolve(admin, back)), worktree)) await rm(admin, { recursive: true, force: true }).catch(() => {});
  };
  const leftover = async () => await exists(temp) || (await execute('git', ['-C', folder, 'worktree', 'list', '--porcelain']).catch(() => ''))
    .split(/\r?\n/).some(line => line.startsWith('worktree ') && same(line.slice(9), worktree));
  for (let attempt = 0; attempt < 2; attempt++) {
    if (attempt) await new Promise(resolve => setTimeout(resolve, 500));
    await execute('git', ['-C', folder, 'worktree', 'remove', '--force', worktree]).catch(() => {});
    await rm(temp, { recursive: true, force: true }).catch(() => {});
    if (!await exists(worktree)) await dropAdmin();
    if (!await leftover()) return;
  }
  say(`warning, could not remove temporary worktree ${temp}; remove it by hand`);
}

// selection: [{ id, apply: [skill], remove: [skill], replace: [{ name, trees }] }]. Every choice is re-checked against a fresh
// fetch, so a skill edited on GitHub since the scan is skipped rather than overwritten. The skip list
// and GitHub's archived flag are checked again here, whatever the scan said.
export async function applySkills({ root, selection, execute = run, template: opened, cache, source, skip, onOutput = () => {} }) {
  const skipList = skip ?? await readSkipList();
  const template = opened ?? await openTemplate({ cache, source, execute, onOutput });
  const clones = new Map((await findClones({ root, execute })).map(clone => [clone.id, clone]));
  const results = [];
  for (const { id, apply = [], remove = [], replace = [] } of selection) {
    const clone = clones.get(id), listed = skipReason(skipList, id);
    if (!clone) { results.push({ id, result: 'failed', error: 'No clone in the CoreWise folder.' }); onOutput(`${id}: no clone in the CoreWise folder\n`); continue; }
    if (listed !== null) { results.push({ id, result: 'failed', error: `Skipped: ${listed}.` }); onOutput(`${id}: skipped, ${listed}; nothing written\n`); continue; }
    try { results.push(await applyRepo({ template, clone, skipList, apply, remove, replace, execute, onOutput })); }
    catch (error) { const message = reason(error); results.push({ id, result: 'failed', error: message, ...(error.branch && { branch: error.branch }), ...(error.url && { url: error.url }) }); onOutput(`${id}: failed${error.branch ? '' : ', nothing pushed'}. ${message}\n`); }
  }
  const failed = results.filter(result => result.result === 'failed');
  if (failed.length) throw Object.assign(new Error(`${failed.length} of ${results.length} repositories failed: ${failed.map(result => result.id).join(', ')}`), { results });
  const prs = results.filter(result => result.result === 'merged').length;
  onOutput(`Done. ${prs} ${prs === 1 ? 'pull request' : 'pull requests'} merged, ${results.filter(result => result.result === 'current').length} already current.\n`);
  return results;
}

// Locks or unlocks one skill in one repository: edits .agents/skill-locks.json in a temporary worktree
// on origin/main and merges it through a pull request, the same way a sync does. The skip list and
// GitHub's archived flag are checked here too. Returns { id, result: 'merged' | 'current', url? }.
export async function setSkillLock({ root, id, skill, lock, reason: why = '', execute = run, skip, onOutput = () => {} }) {
  const say = text => onOutput(`${id}: ${text}\n`);
  const skipList = skip ?? await readSkipList();
  const clone = (await findClones({ root, execute })).find(item => item.id === id);
  if (!clone) throw new Error('No clone in the CoreWise folder.');
  const github = await githubState(id, execute);
  const listed = skipReason(skipList, id) ?? (github.name ? skipReason(skipList, github.name) : null);
  if (listed !== null) throw new Error(`Skipped: ${listed}. Nothing was written.`);
  if (github.skipped) throw new Error(`Skipped: ${github.skipped}. Nothing was written.`);
  if (github.blocked) throw new Error(github.blocked);
  await execute('git', ['-C', clone.folder, ...GIT_CRED, 'fetch', '--quiet', 'origin', 'main']);
  const head = (await execute('git', ['-C', clone.folder, 'rev-parse', 'origin/main'])).trim();
  const temp = await realpath(await mkdtemp(path.join(tmpdir(), 'corewise-lock-')));
  const worktree = path.join(temp, 'work');
  const git = args => execute('git', ['-C', worktree, ...args]);
  try {
    await execute('git', ['-C', clone.folder, 'worktree', 'add', '--quiet', '--detach', worktree, head]);
    const full = path.join(worktree, ...LOCKS.split('/'));
    // A tracked link would send the write outside the temporary checkout.
    for (const where of [path.dirname(full), full]) if ((await lstat(where).catch(() => null))?.isSymbolicLink()) throw new Error(`${path.relative(worktree, where).replaceAll('\\', '/')} is a link in this repository; edit ${LOCKS} by hand.`);
    const locks = await exists(full) ? parseLocks(await readFile(full, 'utf8')) : new Map();
    if (lock ? locks.get(skill) === why : !locks.has(skill)) { say(`${skill} is already ${lock ? 'locked' : 'unlocked'}`); return { id, result: 'current' }; }
    if (lock) locks.set(skill, why); else locks.delete(skill);
    await mkdir(path.dirname(full), { recursive: true });
    await writeFile(full, `${JSON.stringify({ version: 1, locks: Object.fromEntries([...locks].sort(([a], [b]) => a < b ? -1 : a > b ? 1 : 0)) }, null, 2)}\n`);
    await git(['add', '--', LOCKS]);
    const title = lock ? `Lock ${skill} against skill sync` : `Unlock ${skill} for skill sync`;
    const detail = lock ? `Harness Console skill sync leaves ${skill} as it is in this repository${why ? `: ${why}` : ''}.` : `Harness Console skill sync can update ${skill} again.`;
    await git(['commit', '-q', '-m', title, '-m', detail]);
    const commit = (await git(['rev-parse', 'HEAD'])).trim();
    const { branch, url } = await mergeCommit({ git, execute, worktree, github, commit, base: `harness-lock/${skill}`, title, body: `${detail}\n\nThe list is ${LOCKS}.\n\nOpened by Harness Console skill sync.`, say });
    say(`merged ${url} (${lock ? 'locked' : 'unlocked'} ${skill})`);
    return { id, result: 'merged', commit, branch, url };
  } finally {
    await removeWorktree(clone.folder, temp, worktree, execute, say);
  }
}
export function normalizeLock(body) {
  validateRepo(body?.id);
  if (typeof body.skill !== 'string' || !SKILL_NAME.test(body.skill)) throw new Error('Invalid skill name.');
  if (typeof body.lock !== 'boolean') throw new Error('Choose lock or unlock.');
  const why = body.reason === undefined ? '' : body.reason;
  if (typeof why !== 'string' || why.length > 300 || /[\r\n]/.test(why)) throw new Error('Keep the reason to one line of at most 300 characters.');
  return { id: body.id, skill: body.skill, lock: body.lock, reason: why.trim() };
}

export function normalizeSelection(value) {
  if (!Array.isArray(value) || !value.length || value.length > 200) throw new Error('Choose skills to sync.');
  const names = list => { if (list === undefined) return []; if (!Array.isArray(list) || list.some(name => typeof name !== 'string' || !SKILL_NAME.test(name))) throw new Error('Invalid skill name.'); return [...new Set(list)]; };
  const seen = new Set();
  return value.map(item => {
    if (!item || typeof item !== 'object') throw new Error('Choose skills to sync.');
    validateRepo(item.id); if (seen.has(item.id)) throw new Error('Repository listed twice.'); seen.add(item.id);
    return { id: item.id, apply: names(item.apply), remove: names(item.remove), replace: names(item.replace) };
  });
}
