import { spawn } from 'node:child_process';
import { access, lstat, mkdir, mkdtemp, readdir, readFile, realpath, rm, writeFile } from 'node:fs/promises';
import { homedir, tmpdir } from 'node:os';
import path from 'node:path';
import { run, validateRepo } from './core.mjs';
import { TEMPLATE } from './harness.mjs';

// Skill sync: compares every Harness repository cloned under root with the template's main and
// pushes selected skill updates straight to each repository's main. Status comes from git tree
// hashes: a local skill folder whose tree matches some past template version was never edited,
// so replacing it with the current version loses nothing. Anything else is left alone.

export const GIT_CRED = ['-c', 'credential.helper=', '-c', 'credential.helper=!gh auth git-credential'];
const PARTS = ['.claude/skills', '.agents/skills'];
const REGISTRIES = ['.agents/skill-modes.json', '.agents/skill-capabilities.json'];
const SKILL_NAME = /^[A-Za-z0-9_-]+$/;
// Marks a Codex adapter the repository's own generator writes (and rebuilds); same test it uses.
const ADAPTER_MARKER = '<!-- Generated by .claude/scripts/sync-codex-skills.mjs. Do not edit. -->';
const exists = target => access(target).then(() => true, () => false);

export const TEMPLATE_CACHE = path.join(homedir(), '.corewise-cloner', 'harness-firmware.git');

// Reads many blobs through one `git cat-file --batch` process: "<sha> blob <size>\n<bytes>\n" each.
export function readBlobs(cache, shas) {
  return new Promise((resolve, reject) => {
    const child = spawn('git', ['--git-dir', cache, 'cat-file', '--batch'], { windowsHide: true, shell: false, stdio: ['pipe', 'pipe', 'pipe'] });
    const chunks = []; let stderr = '';
    child.stdout.on('data', data => chunks.push(data));
    child.stderr.on('data', data => { stderr += data; });
    child.on('error', reject);
    child.on('close', code => {
      if (code !== 0) return reject(new Error(stderr.trim() || `git cat-file exited with code ${code}`));
      const out = Buffer.concat(chunks), blobs = new Map(); let at = 0;
      while (at < out.length) {
        const newline = out.indexOf(10, at); const [sha, type, size] = out.subarray(at, newline).toString().split(' ');
        if (type !== 'blob') return reject(new Error(`Template object ${sha} is ${type ?? 'missing'}.`));
        blobs.set(sha, out.subarray(newline + 1, newline + 1 + Number(size))); at = newline + 2 + Number(size);
      }
      resolve(blobs);
    });
    child.stdin.end(shas.map(sha => `${sha}\n`).join(''));
  });
}
// A failed Node script's stderr starts with its stack location; the useful line names the error.
const reason = error => { const lines = String(error.message).split(/\r?\n/).map(line => line.trim()).filter(Boolean); return (lines.find(line => /^\w*Error:/.test(line)) ?? lines[0] ?? 'unknown error').replace(/^Error:\s*/, ''); };

// `git ls-tree -z` rows: "<mode> <type> <sha>\t<path>".
export function parseTree(text) {
  return text.split('\0').filter(Boolean).map(row => {
    const tab = row.indexOf('\t'); const [mode, type, sha] = row.slice(0, tab).split(' ');
    return { mode, type, sha, path: row.slice(tab + 1) };
  });
}
// Skill folder tree hashes under both skill roots: { '.claude/skills': Map(name -> sha), ... }.
// A file, symlink or submodule at a skill path lands in odd ('<part>/<name>'): it is not a folder
// the template ever had, so treating it as absent would let a sync overwrite or delete it.
async function skillTrees(git, rev) {
  const trees = Object.fromEntries(PARTS.map(part => [part, new Map()])); trees.odd = new Set();
  for (const entry of parseTree(await git(['ls-tree', '-z', rev, ...PARTS.map(part => `${part}/`)]).catch(() => ''))) {
    const part = PARTS.find(prefix => entry.path.startsWith(`${prefix}/`)); const name = entry.path.slice(part.length + 1);
    if (!SKILL_NAME.test(name)) continue;
    if (entry.type === 'tree') trees[part].set(name, entry.sha); else trees.odd.add(`${part}/${name}`);
  }
  return trees;
}
const showJson = async (git, rev, file) => { try { return JSON.parse(await git(['show', `${rev}:${file}`])); } catch { return null; } };

const commitTrees = new Map();
// Fetches the template into a private bare cache (trees only; blobs arrive when a skill is applied)
// and records every tree each skill folder has ever had on main.
export async function openTemplate({ cache = TEMPLATE_CACHE, source = `https://github.com/${TEMPLATE}.git`, execute = run, onOutput = () => {} } = {}) {
  const git = args => execute('git', ['--git-dir', cache, ...args]);
  if (!await exists(path.join(cache, 'HEAD'))) {
    onOutput('Caching the Harness-Firmware template…\n');
    await mkdir(path.dirname(cache), { recursive: true });
    await execute('git', [...GIT_CRED, 'clone', '--bare', '--quiet', '--filter=blob:none', '--config', 'credential.helper=', '--config', 'credential.helper=!gh auth git-credential', '--', source, cache]);
  } else {
    await git([...GIT_CRED, 'fetch', '--quiet', '--force', 'origin', '+refs/heads/main:refs/heads/main']);
  }
  const head = (await git(['rev-parse', 'refs/heads/main'])).trim();
  const history = Object.fromEntries(PARTS.map(part => [part, new Map()]));
  const commits = (await git(['log', '--format=%H', head, '--', ...PARTS])).split(/\r?\n/).filter(Boolean);
  for (let index = 0; index < commits.length; index += 8) {
    await Promise.all(commits.slice(index, index + 8).map(async commit => { if (!commitTrees.has(commit)) commitTrees.set(commit, await skillTrees(git, commit)); }));
  }
  for (const commit of commits) for (const part of PARTS) for (const [name, sha] of commitTrees.get(commit)[part]) {
    if (!history[part].has(name)) history[part].set(name, new Set());
    history[part].get(name).add(sha);
  }
  const modes = (await showJson(git, head, '.agents/skill-modes.json'))?.skills ?? {};
  const registries = Object.fromEntries(await Promise.all(REGISTRIES.map(async file => [file, await showJson(git, head, file)])));
  return { cache, head, git, current: await skillTrees(git, head), history, modes, registries, blobs: new Map() };
}

// Only real GitHub remotes: https (userinfo allowed), scp-style git@, or ssh://git@. Anchoring the
// host keeps look-alikes (notgithub.com, github.com.evil.test, a path containing github.com) out.
const GITHUB_URLS = [
  // Userinfo is limited to RFC 3986 characters: '#', '?' or '\' before '@' end the authority, so
  // git would connect to the host written before them, not github.com.
  /^https:\/\/(?:[A-Za-z0-9._~%!$&'()*+,;=:-]+@)?github\.com\/([^/\s]+\/[^/\s]+?)(?:\.git)?\/?$/i,
  /^git@github\.com:([^/\s]+\/[^/\s]+?)(?:\.git)?\/?$/i,
  /^ssh:\/\/git@github\.com\/([^/\s]+\/[^/\s]+?)(?:\.git)?\/?$/i,
];
export const githubId = url => { const text = String(url).trim(); for (const pattern of GITHUB_URLS) { const match = pattern.exec(text); if (match) return match[1]; } return null; };

// Git clones directly under root whose origin is a GitHub repository other than the template.
// Two folders on the same repository collapse to one, preferring the folder named after it.
export async function findClones({ root, execute = run, template = TEMPLATE }) {
  const found = new Map();
  for (const entry of await readdir(root, { withFileTypes: true }).catch(() => [])) {
    if (!entry.isDirectory()) continue;
    const folder = path.join(root, entry.name);
    if (!await lstat(path.join(folder, '.git')).catch(() => null)) continue;
    const id = githubId(await execute('git', ['-C', folder, 'config', '--get', 'remote.origin.url']).catch(() => ''));
    if (!id || id.toLowerCase() === template.toLowerCase()) continue;
    try { validateRepo(id); } catch { continue; }
    const previous = found.get(id.toLowerCase());
    if (!previous || (entry.name.toLowerCase() === id.split('/')[1].toLowerCase() && previous.name.toLowerCase() !== previous.id.split('/')[1].toLowerCase())) found.set(id.toLowerCase(), { id, name: entry.name, folder });
  }
  return [...found.values()].sort((a, b) => a.id.localeCompare(b.id));
}

// A template without this part of the skill counts as empty, so every local file shows as added.
async function fileDiff(template, git, rev, name, part = PARTS[0]) {
  const list = async (run, tree) => new Map(parseTree(await run(['ls-tree', '-z', '-r', tree])).map(entry => [entry.path, entry.sha]));
  const theirs = template.current[part].has(name) ? await list(template.git, `${template.head}:${part}/${name}`) : new Map();
  const ours = await list(git, `${rev}:${part}/${name}`);
  return {
    changed: [...ours.keys()].filter(file => theirs.has(file) && theirs.get(file) !== ours.get(file)),
    added: [...ours.keys()].filter(file => !theirs.has(file)),
    missing: [...theirs.keys()].filter(file => !ours.has(file)),
  };
}

// Status of every template skill (and every former template skill) in one repository at rev.
// A native Codex copy under .agents/skills is hand-maintained, so it counts as part of the skill.
// Generated adapters are rebuilt by the repository's own generator instead. The repository's own
// Codex mode for a skill wins over the template's; one without skill-modes.json has no native mode,
// and a skill turned off in settings gets no Codex copy.
export async function compareRepo({ template, folder, rev = 'origin/main', execute = run }) {
  const git = args => execute('git', ['-C', folder, ...args]);
  const local = await skillTrees(git, rev);
  const overrides = (await showJson(git, rev, '.claude/settings.json'))?.skillOverrides ?? {};
  const modes = (await showJson(git, rev, '.agents/skill-modes.json'))?.skills;
  const nativeCopies = new Set([...template.current[PARTS[0]].keys()].filter(name => modes && overrides[name] !== 'off' && (modes[name] ?? template.modes[name]) === 'native'));
  const units = name => nativeCopies.has(name) ? PARTS : [PARTS[0]];
  const pristine = (part, name) => local.odd.has(`${part}/${name}`) ? false : !local[part].has(name) ? part !== PARTS[0] : Boolean(template.history[part].get(name)?.has(local[part].get(name)));
  // Whatever the mode, a Codex copy that is neither a past template tree nor a generated adapter
  // was written by hand in this repository, and adding or removing the skill would destroy it.
  // The generator writes SKILL.md alone, so any other file in the folder was added by hand.
  const generated = async name => {
    const entries = parseTree(await git(['ls-tree', '-z', `${rev}:${PARTS[1]}/${name}`]).catch(() => ''));
    if (entries.length !== 1 || entries[0].path !== 'SKILL.md' || entries[0].type !== 'blob' || entries[0].mode === '120000') return false;
    return git(['cat-file', 'blob', entries[0].sha]).then(text => text.includes(ADAPTER_MARKER), () => false);
  };
  const codexSafe = async name => pristine(PARTS[1], name) || await generated(name);
  // An edited skill carries its folder trees, so replacing it can refuse a copy edited again since
  // the check, and whether its Codex copy was written by hand (replacing it drops that copy too).
  const fingerprint = name => PARTS.map(part => local.odd.has(`${part}/${name}`) ? 'file' : local[part].get(name) ?? '-').join(':');
  const edited = async (name, files) => ({ name, status: 'customized', files, trees: fingerprint(name), handCodex: (local[PARTS[1]].has(name) || local.odd.has(`${PARTS[1]}/${name}`)) && !await generated(name) });
  const skills = [];
  for (const name of template.current[PARTS[0]].keys()) {
    // Off wins even over an existing folder: the repository chose not to track this skill.
    if (overrides[name] === 'off') { skills.push({ name, status: 'off' }); continue; }
    if (!local[PARTS[0]].has(name)) {
      if (!local.odd.has(`${PARTS[0]}/${name}`) && await codexSafe(name)) skills.push({ name, status: 'new' });
      // A file where a folder belongs has no per-file diff; the UI then says the copy differs.
      else skills.push(await edited(name, local.odd.has(`${PARTS[1]}/${name}`) || local.odd.has(`${PARTS[0]}/${name}`) ? { changed: [], added: [], missing: [] } : await fileDiff(template, git, rev, name, PARTS[1])));
      continue;
    }
    if (units(name).every(part => local[part].get(name) === template.current[part].get(name))) { skills.push({ name, status: 'same' }); continue; }
    if (units(name).every(part => pristine(part, name))) { skills.push({ name, status: 'behind' }); continue; }
    skills.push(await edited(name, await fileDiff(template, git, rev, name)));
  }
  for (const name of local[PARTS[0]].keys()) {
    if (template.current[PARTS[0]].has(name) || !template.history[PARTS[0]].has(name)) continue;
    skills.push({ name, status: pristine(PARTS[0], name) && await codexSafe(name) ? 'removed' : 'removed-edited' });
  }
  const harness = [...local[PARTS[0]].keys()].some(name => template.history[PARTS[0]].has(name));
  return { harness, nativeCopies, skills: skills.sort((a, b) => a.name.localeCompare(b.name)) };
}

// Checkouts of a clone (its own folder and every linked worktree) whose committed skill copies are
// an older template version than the repository's main. A session loads skills from its own
// checkout, so a branch cut before a skill sync keeps running old copies while main looks current.
// Copies edited in the branch are not past template trees and are left out. Read-only.
export async function staleWorktrees({ template, folder, rev = 'origin/main', execute = run }) {
  const git = args => execute('git', ['-C', folder, ...args]);
  const main = await skillTrees(git, rev);
  const entries = (await git(['worktree', 'list', '--porcelain']).catch(() => '')).split(/\r?\n\r?\n/).map(block => Object.fromEntries(block.split(/\r?\n/).filter(Boolean).map(line => {
    const at = line.indexOf(' '); return at < 0 ? [line, true] : [line.slice(0, at), line.slice(at + 1)];
  })));
  const found = [];
  for (const entry of entries) {
    if (!entry.worktree || !entry.HEAD || entry.bare || entry.prunable || !await exists(entry.worktree)) continue;
    const trees = await skillTrees(git, entry.HEAD);
    const skills = new Set();
    for (const part of PARTS) for (const [name, sha] of trees[part]) {
      const current = template.current[part].get(name);
      if (current && sha !== current && sha !== main[part].get(name) && template.history[part].get(name)?.has(sha)) skills.add(name);
    }
    if (!skills.size) continue;
    const where = path.resolve(entry.worktree);
    found.push({ path: where, own: where.toLowerCase() === path.resolve(folder).toLowerCase(), branch: entry.branch ? entry.branch.replace(/^refs\/heads\//, '') : null, head: entry.HEAD.slice(0, 7), skills: [...skills].sort() });
  }
  return found;
}

async function limit(items, size, work) {
  const results = new Array(items.length); let next = 0;
  await Promise.all(Array.from({ length: Math.min(size, items.length) }, async () => { while (next < items.length) { const index = next++; results[index] = await work(items[index]); } }));
  return results;
}

// Fetches each clone's origin/main (the working folder itself is never touched) and compares it.
export async function scanSkills({ root, execute = run, template: opened, cache, source } = {}) {
  const template = opened ?? await openTemplate({ cache, source, execute });
  const clones = await findClones({ root, execute });
  const repos = await limit(clones, 6, async clone => {
    try {
      await execute('git', ['-C', clone.folder, ...GIT_CRED, 'fetch', '--quiet', 'origin', 'main']);
      const head = (await execute('git', ['-C', clone.folder, 'rev-parse', 'origin/main'])).trim();
      const worktrees = await staleWorktrees({ template, folder: clone.folder, execute }).catch(() => []);
      return { ...clone, head, ...await compareRepo({ template, folder: clone.folder, execute }), worktrees };
    } catch (error) { return { ...clone, harness: true, error: reason(error) }; }
  });
  return { template: { id: TEMPLATE, head: template.head }, repos: repos.filter(repo => repo.harness).map(({ harness, nativeCopies, ...repo }) => repo) };
}

// Template files under the given skill folders at head, contents fetched in one round trip.
async function templateFiles(template, folders, execute) {
  if (!folders.length) return [];
  const entries = parseTree(await template.git(['ls-tree', '-z', '-r', template.head, '--', ...folders.map(folder => `${folder}/`)]));
  const odd = entries.find(entry => entry.type !== 'blob' || entry.mode === '120000');
  if (odd) throw new Error(`${odd.path} is not a regular file; sync it by hand.`);
  const missing = [...new Set(entries.filter(entry => !template.blobs.has(entry.sha)).map(entry => entry.sha))];
  // The cache is blobless: fetch missing files in batches instead of one lazy fetch per file.
  // A failed batch fetch is not fatal; cat-file still fetches lazily what is absent.
  for (let index = 0; index < missing.length; index += 200) await execute('git', ['--git-dir', template.cache, ...GIT_CRED, 'fetch', '--quiet', '--no-write-fetch-head', 'origin', ...missing.slice(index, index + 200)]).catch(() => {});
  if (missing.length) for (const [sha, data] of await readBlobs(template.cache, missing)) template.blobs.set(sha, data);
  return entries;
}

// Replaces whole skill folders: dropped folders go, template folders arrive byte for byte.
async function writeFolders(template, worktree, git, replace, drop, execute) {
  const entries = await templateFiles(template, replace, execute);
  // git add fails on a pathspec that matches nothing, so only folders that exist before or after count.
  const staged = [...replace];
  for (const folder of [...replace, ...drop]) {
    const full = path.join(worktree, ...folder.split('/'));
    if (drop.includes(folder) && await exists(full)) staged.push(folder);
    await rm(full, { recursive: true, force: true });
  }
  for (const entry of entries) {
    const target = path.join(worktree, ...entry.path.split('/'));
    await mkdir(path.dirname(target), { recursive: true });
    await writeFile(target, template.blobs.get(entry.sha));
  }
  if (staged.length) await git(['add', '-A', '--', ...staged]);
  const executable = entries.filter(entry => entry.mode === '100755').map(entry => entry.path);
  if (executable.length) await git(['update-index', '--chmod=+x', '--', ...executable]);
}

// Copies or drops a skill's registry entries so the repository's Codex checks stay consistent.
// A Codex mode or ownership the repository already chose is kept; the template fills in the rest.
async function writeRegistries(template, worktree, updates) {
  for (const file of REGISTRIES) {
    const full = path.join(worktree, ...file.split('/'));
    if (!await exists(full)) continue;
    const text = await readFile(full, 'utf8'); const data = JSON.parse(text);
    if (!data.skills || typeof data.skills !== 'object') continue;
    for (const [name, keep] of updates) {
      const entry = template.registries[file]?.skills?.[name], mine = data.skills[name];
      if (!keep) delete data.skills[name];
      else if (entry === undefined || (mine !== undefined && typeof mine !== 'object')) continue;
      else data.skills[name] = mine === undefined ? entry : { ...entry, ...(mine.owners && { owners: mine.owners }), ...(mine.coverage && { coverage: mine.coverage }) };
    }
    const next = `${JSON.stringify(data, null, 2)}\n`;
    if (JSON.stringify(JSON.parse(text)) !== JSON.stringify(data)) await writeFile(full, next);
  }
}

const node = (script, args, cwd, execute) => execute(process.execPath, [script, ...args], { cwd }).then(() => true, error => error);

// Applies one repository's selection in a temporary worktree on origin/main and pushes to main.
async function applyRepo({ template, clone, apply, remove, replace, execute, onOutput }) {
  const say = text => onOutput(`${clone.id}: ${text}\n`);
  await execute('git', ['-C', clone.folder, ...GIT_CRED, 'fetch', '--quiet', 'origin', 'main']);
  const head = (await execute('git', ['-C', clone.folder, 'rev-parse', 'origin/main'])).trim();
  const { skills, nativeCopies } = await compareRepo({ template, folder: clone.folder, rev: head, execute });
  const status = new Map(skills.map(skill => [skill.name, skill.status])), found = new Map(skills.map(skill => [skill.name, skill]));
  const take = apply.filter(name => ['behind', 'new'].includes(status.get(name)));
  const drop = remove.filter(name => status.get(name) === 'removed');
  // An edited copy is replaced only while it is still the copy the check saw.
  const swap = replace.filter(({ name, trees }) => status.get(name) === 'customized' && found.get(name).trees === trees).map(({ name }) => name);
  for (const name of [...apply, ...remove].filter(name => !take.includes(name) && !drop.includes(name))) say(`skipped ${name}, now ${status.get(name) ?? 'absent'} on GitHub`);
  for (const { name } of replace.filter(({ name }) => !swap.includes(name))) say(`skipped ${name}, ${status.get(name) === 'customized' ? 'edited again on GitHub since the check' : `now ${status.get(name) ?? 'absent'} on GitHub`}`);
  if (!take.length && !drop.length && !swap.length) { say('nothing to apply'); return { id: clone.id, result: 'current' }; }

  // The long form, so it matches the path `git worktree list` prints when checking cleanup.
  const temp = await realpath(await mkdtemp(path.join(tmpdir(), 'corewise-sync-')));
  const worktree = path.join(temp, 'work');
  const git = args => execute('git', ['-C', worktree, ...args]);
  try {
    await execute('git', ['-C', clone.folder, 'worktree', 'add', '--quiet', '--detach', worktree, head]);
    const scripts = { codex: path.join(worktree, '.claude', 'scripts', 'sync-codex-skills.mjs'), capabilities: path.join(worktree, '.claude', 'scripts', 'check-skill-capabilities.mjs') };
    const hasCodex = await exists(scripts.codex);
    const hasCapabilities = await exists(scripts.capabilities) && await exists(path.join(worktree, '.agents', 'skill-capabilities.json'));
    const before = { codex: hasCodex && await node(scripts.codex, ['--check'], worktree, execute), capabilities: hasCapabilities && await node(scripts.capabilities, [], worktree, execute) };

    // Only skills whose Codex copy is native here receive the template's .agents folder.
    // A replaced skill loses a hand-written Codex copy the template does not supply, so the repository's
    // generator can write its adapter; a generated adapter stays for the generator to rebuild.
    const incoming = name => PARTS.filter(part => template.current[part].has(name) && (part === PARTS[0] || nativeCopies.has(name)));
    const folders = [...take, ...swap].flatMap(name => incoming(name).map(part => `${part}/${name}`));
    const handDrops = swap.filter(name => found.get(name).handCodex && !incoming(name).includes(PARTS[1])).map(name => `${PARTS[1]}/${name}`);
    await writeFolders(template, worktree, git, folders, [...drop.flatMap(name => PARTS.map(part => `${part}/${name}`)), ...handDrops], execute);
    await writeRegistries(template, worktree, [...take, ...swap].map(name => [name, true]).concat(drop.map(name => [name, false])));

    // The repository's own generators rebuild Codex adapters and the capability catalog. A check
    // that passed before this change must still pass after it, or nothing is pushed.
    if (hasCodex) {
      const wrote = await node(scripts.codex, ['--write'], worktree, execute);
      const after = wrote === true ? await node(scripts.codex, ['--check'], worktree, execute) : wrote;
      if (after !== true && before.codex === true) throw new Error(`sync-codex-skills.mjs fails after the change: ${reason(after)}`);
      if (after !== true) say('sync-codex-skills.mjs was already failing on main; pushed anyway');
    }
    if (hasCapabilities) {
      await node(scripts.capabilities, ['--write'], worktree, execute);
      const after = await node(scripts.capabilities, [], worktree, execute);
      if (after !== true && before.capabilities === true) throw new Error(`check-skill-capabilities.mjs fails after the change: ${reason(after)}`);
      if (after !== true) say('check-skill-capabilities.mjs was already failing on main; pushed anyway');
    }

    await git(['add', '-A']);
    if (await git(['diff', '--cached', '--quiet']).then(() => true, () => false)) { say('already current'); return { id: clone.id, result: 'current' }; }
    const updated = take.filter(name => status.get(name) === 'behind'), added = take.filter(name => status.get(name) === 'new');
    const body = [updated.length && `Updated: ${updated.join(', ')}`, added.length && `Added: ${added.join(', ')}`, swap.length && `Replaced edited copies: ${swap.join(', ')}`, drop.length && `Removed: ${drop.join(', ')}`, `Template: ${TEMPLATE}@${template.head.slice(0, 7)}`].filter(Boolean).join('\n');
    await git(['commit', '-q', '-m', 'Sync skills from Harness-Firmware', '-m', body]);
    const commit = (await git(['rev-parse', 'HEAD'])).trim();
    await git([...GIT_CRED, 'push', '--quiet', 'origin', 'HEAD:refs/heads/main']);
    say(`pushed ${commit.slice(0, 7)} to main (${body.split('\n').slice(0, -1).join('; ')})`);
    return { id: clone.id, result: 'pushed', commit };
  } finally {
    await removeWorktree(clone.folder, temp, worktree, execute, say);
  }
}

// An editor or virus scanner holding a file open can block removal for a moment, so retry once;
// whatever still remains is named so it can be removed by hand instead of piling up unseen.
// Never a blanket `git worktree prune`: that would also drop the user's own stale registrations
// (a worktree on an unplugged drive). Only this worktree's admin entry goes, and only unlocked,
// the same rule prune follows.
async function removeWorktree(folder, temp, worktree, execute, say) {
  const same = (a, b) => path.resolve(a).toLowerCase() === path.resolve(b).toLowerCase();
  // The worktree's .git file names its admin entry (<common dir>/worktrees/<id>); read it before removal.
  const pointer = await readFile(path.join(worktree, '.git'), 'utf8').then(text => /^gitdir:\s*(.+)$/m.exec(text)?.[1].trim(), () => null);
  const admin = pointer && path.resolve(worktree, pointer);
  const dropAdmin = async () => {
    if (!admin || await exists(path.join(admin, 'locked'))) return;
    const back = await readFile(path.join(admin, 'gitdir'), 'utf8').then(text => text.trim(), () => null);
    if (back && same(path.dirname(path.resolve(admin, back)), worktree)) await rm(admin, { recursive: true, force: true }).catch(() => {});
  };
  const leftover = async () => await exists(temp) || (await execute('git', ['-C', folder, 'worktree', 'list', '--porcelain']).catch(() => ''))
    .split(/\r?\n/).some(line => line.startsWith('worktree ') && same(line.slice(9), worktree));
  for (let attempt = 0; attempt < 2; attempt++) {
    if (attempt) await new Promise(resolve => setTimeout(resolve, 500));
    await execute('git', ['-C', folder, 'worktree', 'remove', '--force', worktree]).catch(() => {});
    await rm(temp, { recursive: true, force: true }).catch(() => {});
    if (!await exists(worktree)) await dropAdmin();
    if (!await leftover()) return;
  }
  say(`warning, could not remove temporary worktree ${temp}; remove it by hand`);
}

// selection: [{ id, apply: [skill], remove: [skill], replace: [{ name, trees }] }]. Every choice is re-checked against a fresh
// fetch, so a skill edited on GitHub since the scan is skipped rather than overwritten.
export async function applySkills({ root, selection, execute = run, template: opened, cache, source, onOutput = () => {} }) {
  const template = opened ?? await openTemplate({ cache, source, execute, onOutput });
  const clones = new Map((await findClones({ root, execute })).map(clone => [clone.id, clone]));
  const results = [];
  for (const { id, apply = [], remove = [], replace = [] } of selection) {
    const clone = clones.get(id);
    if (!clone) { results.push({ id, result: 'failed', error: 'No clone in the CoreWise folder.' }); onOutput(`${id}: no clone in the CoreWise folder\n`); continue; }
    try { results.push(await applyRepo({ template, clone, apply, remove, replace, execute, onOutput })); }
    catch (error) { const message = reason(error); results.push({ id, result: 'failed', error: message }); onOutput(`${id}: failed, nothing pushed. ${message}\n`); }
  }
  const failed = results.filter(result => result.result === 'failed');
  if (failed.length) throw Object.assign(new Error(`${failed.length} of ${results.length} repositories failed: ${failed.map(result => result.id).join(', ')}`), { results });
  onOutput(`Done. ${results.filter(result => result.result === 'pushed').length} pushed, ${results.filter(result => result.result === 'current').length} already current.\n`);
  return results;
}

export function normalizeSelection(value) {
  if (!Array.isArray(value) || !value.length || value.length > 200) throw new Error('Choose skills to sync.');
  const names = list => { if (list === undefined) return []; if (!Array.isArray(list) || list.some(name => typeof name !== 'string' || !SKILL_NAME.test(name))) throw new Error('Invalid skill name.'); return [...new Set(list)]; };
  const seen = new Set();
  return value.map(item => {
    if (!item || typeof item !== 'object') throw new Error('Choose skills to sync.');
    validateRepo(item.id); if (seen.has(item.id)) throw new Error('Repository listed twice.'); seen.add(item.id);
    return { id: item.id, apply: names(item.apply), remove: names(item.remove), replace: names(item.replace) };
  });
}
