// Assembles README.md from the facts and the generated panels.
// The top third is the showpiece; below it the README still answers what
// this is, how to run it, and what it touches, in plain markdown.

import fs from "node:fs";
import path from "node:path";
import { ROOT, collectFacts } from "./facts.mjs";
import { picture } from "./lib.mjs";

const F = collectFacts();
export const MARKER = "<!-- generated by scripts/readme/build.mjs. do not edit by hand. -->";

const endpointRows = F.endpoints.map((e) => `| \`${e.method} ${e.host}${e.path}\` | ${e.what} |`).join("\n");

const md = `${MARKER}

${picture("masthead", `UsageTracker: rate-limit windows, reset clocks and token totals for every Claude Code and Codex account on this machine. ${F.claudeWindows.length} Claude windows polled every ${F.claudePollSeconds} seconds, 2 Codex windows every ${F.codexPollSeconds} seconds, token totals rescanned every ${F.tokenScanSeconds} seconds, one write: the Claude token refresh.`)}

UsageTracker serves one local page for every Claude Code and Codex account on the machine: how much of each rate-limit window is used, when it resets, and the tokens each provider burned over the last 7, 30 or 90 days. It reads the credential files the CLIs write on login and the transcripts they leave on disk. The one write is the Claude token refresh. Node only, ${F.sourceFiles} source files, no dependencies.

## Run

Node 20 or newer, nothing to install.

\`\`\`bash
node server.mjs
\`\`\`

Open http://127.0.0.1:${F.port}. The page refetches every ${F.pageFetchSeconds} seconds and the reset countdowns tick every ${F.countdownSeconds}; "Refresh now" polls every account and rescans transcripts at once.

## Accounts

\`accounts.json\` lists one entry per account:

\`\`\`json
{ "name": "Claude 2", "kind": "claude", "dir": "~/.claude-2" }
\`\`\`

- \`kind: "claude"\` reads \`<dir>/.credentials.json\`, the file Claude Code writes on login.
- \`kind: "codex"\` reads \`<dir>/auth.json\`, the file Codex writes on login.

Each account needs its own directory so its credentials survive a login elsewhere. The first account of each kind uses the default directory (\`~/.claude\`, \`~/.codex\`). Log a second account into a separate directory once:

\`\`\`bash
$env:CLAUDE_CONFIG_DIR = "C:\\Users\\Home\\.claude-2"; claude login
\`\`\`

\`\`\`bash
$env:CODEX_HOME = "C:\\Users\\Home\\.codex-2"; codex login
\`\`\`

The tracker never switches accounts; it only reads.

## What it shows

| Provider | Windows | Extras |
|---|---|---|
| Claude Code | ${F.claudeWindows.join(", ")} (the last two when the plan reports them) | plan tier and email; extra-usage credits when enabled |
| Codex | Session and Weekly, whichever the API reports as active | plan and email; credit balance; banked rate-limit resets with their expiry dates |

Bars turn amber at ${F.warnAt}% used and red at ${F.badAt}%. A card with a red border shows the last error; if an earlier fetch succeeded, the old numbers stay visible with their age.

## Token totals

Neither provider reports token counts over an API, so the tracker reads the transcripts the CLIs write on this machine: \`<dir>/projects/**/*.jsonl\` for Claude Code, \`<dir>/sessions/**/*.jsonl\` for Codex. Transcripts carry no account identifier, and logging out and back in with another email puts both accounts' sessions in the same directory, so totals are shown per provider, combined across accounts. Sessions run on other machines are not counted.

Each provider panel shows the total, split into uncached input, cache reads, cache writes and output, with the top three models and a bar per day. Under it sits an API-equivalent dollar figure, which prices the same traffic at public API rates from [LiteLLM's table](https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json), fetched once a day and cached in \`.state/pricing.json\`. It is not a subscription bill. Models missing from the table show as unpriced unless \`priceAliases\` in \`accounts.json\` maps them to a priced model, for example \`"codex-auto-review": "gpt-5.6-sol"\` for Codex's internal reviewer.

Parsing follows [T3 Code](https://github.com/pingdotgg/t3code) (MIT) and ccusage: Claude lines are deduplicated by message id and request id (one message spans several transcript lines), Codex totals sum \`last_token_usage\` deltas with re-emitted duplicates dropped, and the parent history copied into a forked Codex rollout is skipped.

Parsed records are cached per file in \`.state/tokens/\`, keyed by size and mtime, so a rescan (every ${F.tokenScanSeconds} seconds, \`tokenScanSeconds\` in \`accounts.json\`) reads only files that changed, and a grown file only from where the last read stopped. Records are kept ${F.retentionDays} days after the CLI deletes the transcript, so history outlives Claude Code's \`cleanupPeriodDays\` (default 30; raise it in \`settings.json\` so the first scan can backfill further).

## Tokens and polling

- Claude access tokens expire after a few hours. When one is expired, the tracker refreshes it with the stored refresh token (same endpoint and client id the CLI uses) and writes the new token back to that account's \`.credentials.json\`, atomically. This is the only write the tracker performs. If the refresh token itself is rejected, the card says to run \`claude\` in that directory.
- Codex access tokens last about ten days and the CLI refreshes them on use. The tracker never refreshes Codex tokens; it warns ${F.codexExpiryWarnHours} hours before expiry.
- Claude is polled every ${F.claudePollSeconds} seconds per account (the usage endpoint rate-limits faster polling), Codex every ${F.codexPollSeconds}. Both are configurable in \`accounts.json\` via \`claudePollSeconds\` and \`codexPollSeconds\`. The last good snapshot per account is cached in \`.state/\` so the page shows data right after a restart.

## Endpoints used

| Call | Purpose |
|---|---|
${endpointRows}

The vendor calls are not documented public APIs. They are the same calls the CLIs and [CodexBar](https://github.com/steipete/CodexBar) make; request shapes were taken from [Win-CodexBar](https://github.com/nesszer/Win-CodexBar) (MIT), and either vendor can change them without notice.

## README

\`README.md\` and \`assets/readme/*.svg\` are generated: \`node scripts/readme/build.mjs\` reads the numbers out of the source files and fails if any drift. Edit \`scripts/readme/\`, not the output. The repo's About panel (description and topics) comes from \`scripts/readme/repo.json\`; \`node scripts/readme/meta.mjs --apply\` pushes it, and after a merge CI fails when the live values or the README's remote links no longer answer.

## License

[MIT](LICENSE).
`;

fs.writeFileSync(path.join(ROOT, "README.md"), md, "utf8");
console.log(`readme: ${md.split("\n").length} lines written`);
