// Gate: the generated README and panels still say what the source says.
// Exits non-zero on any mismatch. CI runs this after a fresh build and a
// clean git diff, so a hand edit or a stale number cannot land.

import fs from "node:fs";
import path from "node:path";
import { ROOT, collectFacts } from "./facts.mjs";
import { readmeLinks } from "./lib.mjs";

const F = collectFacts();
const MARKER = "<!-- generated by scripts/readme/build.mjs. do not edit by hand. -->";
let bad = 0;
const fail = (m) => { console.error(`FAIL ${m}`); bad++; };
const asset = (n) => fs.readFileSync(path.join(ROOT, "assets", "readme", n), "utf8");

// Numbers each panel must carry, in every variant.
const NEED = {
  masthead: [`${F.claudePollSeconds} s`, `${F.codexPollSeconds} s`, `${F.tokenScanSeconds} s`, `${F.warnAt}%`, `${F.badAt}%`, `:${F.port}`, ...F.claudeWindows],
};
for (const [name, needs] of Object.entries(NEED)) {
  for (const v of ["light", "dark", "narrow-light", "narrow-dark"]) {
    const file = `${name}-${v}.svg`;
    let text;
    try { text = asset(file); } catch { fail(`missing asset ${file}`); continue; }
    for (const n of needs) if (!text.includes(n)) fail(`${file}: should read ${n}`);
    if (!/prefers-reduced-motion/.test(text)) fail(`${file}: no reduced-motion rule`);
    if (/https?:\/\//.test(text.replace(/xmlns="http:\/\/www\.w3\.org\/2000\/svg"/, ""))) fail(`${file}: external reference`);
  }
}
// Every clock loops: one ring per Claude window, two Codex, three token ranges.
for (const v of ["light", "narrow-light"]) {
  const text = asset(`masthead-${v}.svg`);
  const clocks = (text.match(/class="hand"/g) ?? []).length;
  const expected = F.claudeWindows.length + 2 + 3;
  if (clocks !== expected) fail(`masthead-${v}: ${clocks} clocks, expected ${expected}`);
  if (/font-weight="[5-9]00"|font-weight:[5-9]00|font-weight="bold"/.test(text)) fail(`masthead-${v}: text heavier than 400`);
  if (/animation-iteration-count:(?!infinite)/.test(text)) fail(`masthead-${v}: one-shot animation`);
}

// README invariants.
const md = fs.readFileSync(path.join(ROOT, "README.md"), "utf8");
if (!md.startsWith(MARKER)) fail("README: generated marker missing from line 1");
if (!/^## Run$/m.test(md) || !md.includes("node server.mjs")) fail("README: run section missing");
if (!md.includes("(LICENSE)")) fail("README: license link missing");
for (const m of md.matchAll(/(?:src|srcset)="(assets\/[^"]+)"/g)) if (!fs.existsSync(path.join(ROOT, m[1]))) fail(`README: missing asset ${m[1]}`);
for (const e of F.endpoints) if (!md.includes(`${e.method} ${e.host}${e.path}`)) fail(`README: endpoint ${e.path} not listed`);
for (const name of Object.keys(NEED)) if ((md.split(`assets/readme/${name}-light.svg`).length - 1) !== 1) fail(`README: panel ${name} placed ${md.split(`assets/readme/${name}-light.svg`).length - 1} times`);
if (/—/.test(md)) fail("README: em dash");

// Local link targets exist on disk. Remote links are fetched by meta.mjs --check
// (network, post-merge), so the build itself stays deterministic and offline.
for (const target of readmeLinks(md)) {
  if (/^https?:/.test(target)) continue;
  if (!fs.existsSync(path.join(ROOT, target.split("#")[0]))) fail(`README: link ${target} missing on disk`);
}

if (bad) { console.error(`${bad} problem(s)`); process.exit(1); }
console.log("verify: ok");
